<?php
global $adb,$table_prefix;

// add some extra german translations if german is installed

$language = 'de_de';
$lang_add = array (
  'ALERT_ARR' => 
  array (
    'ANSWER_SENT' => 'Die Antwort wird gesendet wurde',
    'CONFIRM_LINKED_EVENT_DELETION' => 'Haben Sie auch das zugehörige Ereignis zu beseitigen?',
    'ERR_CF' => 'Tax Code ist ungültig!',
    'ERR_PIVA' => 'MwSt ungültig!',
    'LBL_CANT_USE_DEFAULT_MAPPED_FIELD' => 'Sie können nicht eine Standardeinstellung oder zu ändern, um ein Feld, das in der Import abgebildet wird',
    'LBL_CONTINUE_WITHOUT_KEY_FIELD' => 'Nicht ein Feld als Schlüssel noch entschieden. Jeder Import Datensätze werden dem CRM hinzugefügt werden. Bestätigen?',
    'LBL_CSVPATH_MUST_NOT_BE_ABSOLUTE' => 'Der Pfad der CSV-Datei kann nicht absolut sein',
    'LBL_DATA_IMPORT_ABORTED' => 'Der Import wurde abgebrochen. Wenn Sie bereits begonnen, wird sie innerhalb von wenigen Minuten zu stoppen',
    'LBL_DATA_IMPORT_SCHEDULED_NOW' => 'Der Import wurde eingereiht. Innerhalb von wenigen Minuten wird es automatisch gestartet',
    'LBL_FIELD_IS_INVALID' => 'Feld %s ist nicht korrekt',
    'LBL_FIELD_IS_NUMERIC' => 'Feld %s muss eine Zahl sein',
    'LBL_FILL_ALL_FIELDS' => 'Geben Sie Werte für die erforderlichen Felder',
    'LBL_FILTER_FIELD_MORE_THAN_ONCE' => 'Sie haben das gleiche Feld mehr als einmal ausgewählt. Die Felder müssen unterschiedlich sein',
    'LBL_INVALID_VALUE' => 'Ungültiger Wert',
    'LBL_MMAKER_CONFIRM_RESET' => 'Sicher, dass Sie die Dateien in den ursprünglichen Zustand wiederherstellen möchten? Es werden alle Änderungen verlieren.',
    'LBL_NAME' => 'Name',
    'LBL_NAME_S' => 'Benennen Sie %s',
    'LBL_PLEASE_SELECT_MODULE' => 'Wählen Sie ein Modul',
    'LBL_PLEASE_SELECT_VALUE' => 'Wert auswählen',
    'LBL_SAMEMODULERELATED' => 'Das Modul %s ist in mehr als einem Feld Bericht vor. Und \'möglich, nur einen Bericht für jedes Modul angeschlossen',
    'LBL_SELECT_AT_LEAST_ONE_FIELD' => 'Wählen Sie mindestens ein Feld',
    'LBL_SELECT_TABLE_OR_QUERY' => 'Wenn Sie eine benutzerdefinierte Abfrage verwenden möchten, wählen Sie "None" als Tabellen',
    'LBL_SURE_TO_UNINSTALL_MODULE' => 'Deinstallieren des Moduls, wird es alle Datensätze zu entfernen. Gehen Sie?',
    'LBL_TOO_LONG' => '%s ist zu lang',
    'LBL_TOO_MANY_UITYPE4' => 'Und "mehr als ein Feld vom Typ Automatische Nummerierung. E \'kann nur eine pro Modul zu erstellen',
    'LBL_UTF8' => 'Bitte ändern Sie die Konfigurationsdatei (in der Wurzel des vtiger befindet, mit dem Namen config-inc.php), um die UTF-8-Zeichensatz unterstützen und aktualisieren Sie die Seite',
    'LBL_VALUE_TOO_BIG' => 'Wert zu groß',
    'LBL_VALUE_TOO_SMALL' => 'Wert zu klein',
    'LBL_WANT_TO_SAVE_PENDING_CHANGES' => 'Möchten Sie die Änderungen speichern?',
  ),
  'APP_STRINGS' => 
  array (
    'LBL_ABANDON' => 'Verlassen',
    'LBL_ACCEPT_INVITATION' => 'Einladung annehmen',
    'LBL_AREA' => 'Bereich',
    'LBL_ASSOCIATED_MODULE' => 'Zugehörige Modul',
    'LBL_AT_HOUR' => 'bis',
    'LBL_AT_MINUTE' => 'Einzelhandel',
    'LBL_AUTOMATIC' => 'Automatische',
    'LBL_CALENDAR_TRACKING' => 'Tracking',
    'LBL_CHOOSE_FILE' => 'Wählen Sie die Datei',
    'LBL_COPY_FILES_ERROR' => 'Fehler beim Kopieren von Dateien',
    'LBL_DATABASE_NAME' => 'Namensdatenbank',
    'LBL_DATABASE_TYPE' => 'Type Database',
    'LBL_DAY' => 'Day',
    'LBL_DAYS' => 'Tage',
    'LBL_DESCRIPTION_INFORMATION' => 'Informationen Beschreibung',
    'LBL_DIRECTORY_NOT_READABLE' => 'Das Verzeichnis nicht über die Berechtigung zum Lesen',
    'LBL_DIRECTORY_NOT_READABLE_N' => 'Das Verzeichnis %s nicht über die Berechtigung zum Lesen',
    'LBL_DIRECTORY_NOT_WRITEABLE' => 'Das Verzeichnis nicht über Schreibrechte',
    'LBL_DIRECTORY_NOT_WRITEABLE_N' => 'Das Verzeichnis %s nicht über Schreibrechte',
    'LBL_DONE_BUTTON_TITLE' => 'Erledigt',
    'LBL_DO_TRACK' => 'Spur',
    'LBL_DO_TRACK_AND' => 'Track and',
    'LBL_DO_TRACK_AND_TICKET' => 'Track and Ticket',
    'LBL_EJECT_TRACKING' => 'Aus Liste entfernen',
    'LBL_FILE_NOT_READABLE' => 'Die Datei ist nicht lesbar',
    'LBL_FIRST_MODULE' => 'Erste Modul',
    'LBL_HOSTNAME' => 'Host Name',
    'LBL_HOURS' => 'Stunden',
    'LBL_INSTALL' => 'Installieren',
    'LBL_INSTALLATION' => 'Installation',
    'LBL_INSTALLATION_LOGS' => 'Installationsprotokolle',
    'LBL_INSTALLED' => 'Installiert',
    'LBL_KEY_FIELD' => 'Schlüsselfeld',
    'LBL_MINUTE' => 'Minute',
    'LBL_MINUTES' => 'Minuten',
    'LBL_MODULE_EXISTING' => 'Es gibt bereits eine Form mit diesem Namen',
    'LBL_NOT_ALLOWED_OPERATION' => 'Es ist nicht erlaubt, dies zu tun',
    'LBL_NO_SPECIAL_CHARS_IN_FIELD' => 'Sie benutzen keine Sonderzeichen für das Feld %s',
    'LBL_NUMBER_WITH_DECIMALS' => 'Zahl mit Nachkommastellen',
    'LBL_ORGANIZER' => 'Organizer',
    'LBL_PAUSE' => 'Pausieren',
    'LBL_RELATIONS' => 'Beziehungen',
    'LBL_RENAME_FILE_ERROR' => 'Fehler Umbenennungsdatei',
    'LBL_SAVE_FILE' => 'Speichern Sie die Datei',
    'LBL_SELECT_TIME_AND_USERS' => 'Wählen Sie einen Zeitraum und die Benutzer, die Sie einladen möchten.',
    'LBL_SHOW_PREVIEW' => 'Vorschau',
    'LBL_SOURCE' => 'Ursprung',
    'LBL_START' => 'Beginnt',
    'LBL_START_NOW' => 'Jetzt starten',
    'LBL_TOO_LONG' => 'Es ist zu lang',
    'LBL_TRACKER_MODULE' => 'Tracking Aktivitäten',
    'LBL_TRACKING_ALREADY_RUNNING' => 'Bereits läuft für',
    'LBL_TRACKING_ALREADY_RUNNING_BY_USER' => 'Derzeit verfolgt er auch',
    'LBL_TRACKING_MSG_PAUSE' => 'Sehr geehrter Kunde, die Auflösung Ihres Anspruch dauert länger als erwartet, werden wir mit der Untersuchung fort und hält Sie über den Fortschritt aktualisiert.',
    'LBL_TRACKING_MSG_START' => 'Sehr geehrter Kunde, hat der Bericht über die von der zuständigen Abteilung übernommen. Wir halten Sie über den Stand aktualisiert.',
    'LBL_TRACKING_MSG_STOP' => 'Sehr geehrter Kunde, wir fertig sind die Untersuchung auf ihre Berichterstattung, überprüfen Sie bitte die Lösung des Problems.',
    'LBL_TRACKING_NO_ENTRIES' => 'Keine Tracking aktiv oder angehalten',
    'LBL_TRACK_AND_COMMENT' => 'Track und Kommentare',
    'LBL_TRACK_MANAGER' => 'Tracking',
    'LBL_TRACK_MANAGER_TITLE' => 'Striping aktiv oder angehalten',
    'LBL_TRACK_NAME' => 'Route',
    'LBL_TRACK_PAUSE_FOR' => 'Pause Tracking diese',
    'LBL_TRACK_START_FOR' => 'Starten Sie die Ablaufverfolgung für diese',
    'LBL_TRACK_STOP_FOR' => 'Stoppen Sie die Ablaufverfolgung für diese',
    'LBL_UNINSTALL' => 'Uninstall',
    'LBL_UNINSTALLATION' => 'Deinstallieren',
    'LBL_UNIT' => 'Maßeinheit',
    'LBL_UNIT_MEASURE_PR' => 'Maßeinheit',
    'LBL_WHEN' => 'Wann',
    'LBL_WHERE' => 'Wo',
    'Lead Status' => 'Staatsblei',
    'Offline' => 'Offline',
    'SINGLE_Charts' => 'Graphic',
    'Tracking' => 'Route',
  ),
  'Calendar' => 
  array (
    'ANSWER_TO_INVITATION' => 'Antwort auf',
    'LBL_INVITATION_ACCEPTED' => 'Er hat die Einladung zu Ihrem Ereignis akzeptiert.',
    'LBL_INVITATION_ACCEPTED_SUBJECT' => 'Antwort auf die (angenommen)',
    'LBL_INVITATION_DECLINED' => 'Er hat die Einladung zu Ihrem Ereignis zurückgegangen.',
    'LBL_INVITATION_DECLINED_SUBJECT' => 'Rahmen der Ausschreibung (abgelehnt)',
    'LBL_INVITATION_NO' => 'Nicht teil',
    'LBL_INVITATION_YES' => 'Beteiligt',
    'LBL_PREVIEW_INVITATION' => 'Vorschau der Einladung',
    'LBL_VISIT_CANNOT_CLOSE' => 'Nur der Supervisor kann diese Aktivität zu schließen',
    'LBL_VISIT_MUST_RELATED' => 'Diese Art der Veranstaltung muss für ein Unternehmen bezogen werden',
    'Tracked' => 'Route',
    'Visit' => 'Besichtigung',
  ),
  'Documents' => 
  array (
    'DOC_NOT_ACTIVE' => 'Inaktive Datei',
    'DOC_NOT_SUPP' => 'Nicht unterstützte Datei',
    'DOC_PREVIEW' => 'Datei-Vorschau',
    'DOC_PREVIEW_BUTTON' => 'Vorschau',
  ),
  'Emails' => 
  array (
    'MESSAGE_MAIL_SENT_SUCCESSFULLY_ENABLE_CRON' => 'Nachricht wurde gesendet, kann der cron, um Geschwindigkeit Sendungen',
  ),
  'HelpDesk' => 
  array (
    'Acceptance (Abteilungsleiter)' => 'Bestätigung',
    'Berechnung' => 'Berechnung',
    'Confirm' => 'Bestätigung',
    'Datum Acceptance' => 'Bestätigung Datum',
    'Gerechtfertigt' => 'Genehmigt',
    'Med-Gas(Ja/Nein)' => 'Med. Gas',
    'Reassign the ticket' => 'Weist das Ticket',
    'Verantwortlich' => 'Verantwortlich',
    'Verantwortlich EMail' => 'Nachricht an die Agentur',
    'Vorgeschlagene Gutschrift' => 'Vorgeschlagene Kredit',
  ),
  'Invoice' => 
  array (
    'Top Invoices' => 'Mein Haupt offenen Rechnungen',
  ),
  'Messages' => 
  array (
    'LBL_DOWNLOAD_ALL' => 'Laden Sie alle Anhänge',
    'LBL_FILTER_FOLDERS_NOT_FOUND' => 'Einige Filter wurden nicht angewendet, da sie auf vorhandene Ordner beziehen:',
    'LBL_VIEWERJS_DOWNLOAD' => 'Entlastung',
    'LBL_VIEWERJS_FULLSCREEN' => 'Vollbild',
    'LBL_VIEWERJS_NEXT_PAGE' => 'Nächste Seite',
    'LBL_VIEWERJS_PAGE' => 'Page',
    'LBL_VIEWERJS_PRESENTATION' => 'Vorstellung',
    'LBL_VIEWERJS_PREV_PAGE' => 'Zurück',
    'LBL_VIEWERJS_ZOOM' => 'Zoomen',
    'LBL_VIEWERJS_ZOOM_AL' => 'Breite anpassen',
    'LBL_VIEWERJS_ZOOM_AS' => 'Tatsächliche Größe',
    'LBL_VIEWERJS_ZOOM_AUTO' => 'Automatische',
    'LBL_VIEWERJS_ZOOM_IN' => 'Erhöhen Zoom',
    'LBL_VIEWERJS_ZOOM_OUT' => 'Minimieren Zoom',
    'LBL_VIEW_AS_EMAIL' => 'Darstellung als E-Mail',
    'LBL_VIEW_DOCUMENT' => 'Dokument anzeigen',
    'TRANSLATE_MESSAGE' => 'Übersetzen Nachricht',
  ),
  'ModNotifications' => 
  array (
    'added a revision to' => 'Er fügte hinzu, eine Revision',
    'Import Error' => 'Import-Fehler',
  ),
  'Offline' => 
  array (
    'LBL_CHECK_SERVER_BUTTON' => 'prüft Präsenz-Server CRM',
    'LBL_CHECK_SERVER_HELPER' => 'Wenn der Server und "aktiv ist, können Sie den Zugang zu Betriebsdaten-Update',
    'LBL_CHECK_SERVER_KO' => 'Server nicht erreichbar',
    'LBL_CHECK_SERVER_OK' => 'Zum Verfahren zur Aktualisierung des zentralen Systems',
    'LBL_CLIENT_NAME' => 'Offline-Client',
    'LBL_DOWNLOAD_TIME' => 'Daten-Downloads',
    'LBL_EXPIRE_TIME' => 'Ablaufdatum',
    'LBL_GOOFFLINE_DOCUMENT_CONFIRM' => 'Ok',
    'LBL_GOOFFLINE_DOCUMENT_TITLE' => 'Dokumente offline',
    'LBL_LOGIN_OFFLINE' => 'Verwenden Sie das untenstehende Formular aus, um die CRM-Modus "Online-Nutzung',
    'LBL_OFFLINE_ONLINE' => 'Wie Daten aus dem CRM hochgeladen offline',
    'LBL_ONLINE_OFFLINE' => 'Wie man Daten von CRM Online downloaden',
    'LBL_PASSWORD' => 'Passwort',
    'LBL_PROGRESS' => 'Advancement-Prozess',
    'LBL_RESET' => 'Wiederherstellung der Client-',
    'LBL_RESET_BUTTON' => 'Wiederherstellen',
    'LBL_RESET_CANCEL' => 'Nein, ich will zurück zu gehen',
    'LBL_RESET_CONFIRM' => 'Ich bestätige, fahren Sie mit der Restaurierungs-',
    'LBL_RESET_CONFIRM_FORCE' => 'Ok',
    'LBL_RESET_ERROR' => 'Error Recovery',
    'LBL_RESET_HELPER' => 'Wiederherstellung der Client, sobald installiert',
    'LBL_RESET_TITLE' => 'Wollen Sie wirklich, um mit dem Zurücksetzen des Client fortsetzen?',
    'LBL_RESET_TITLE_FORCE' => 'Rücksetzen von Client-',
    'LBL_SERVER_ADDRESS' => 'Adress-Server CRM',
    'LBL_SERVER_NAME' => 'Offline-Servern',
    'LBL_SETTINGS' => 'Client-Einstellungen offline',
    'LBL_STEP1-1_DESC' => 'Authentifizierung zum zentralen CRM und die Schaffung von Daten für die Offline-Migration läuft ...',
    'LBL_STEP1-1_NAME' => 'Fase1-1',
    'LBL_STEP1-1_OL_DESC' => 'Authentifizierung zum zentralen CRM und die Schaffung von Paket-Update ...',
    'LBL_STEP1-1_OL_NAME' => 'Fase1-1',
    'LBL_STEP1_DESC' => 'Zu diesem Zeitpunkt geben Sie die Adresse des Servers, und \'installiert CRM auch Zugangsdaten',
    'LBL_STEP1_NAME' => 'Phase 1',
    'LBL_STEP1_OL_DESC' => 'Zu diesem Zeitpunkt geben Sie die Adresse des Servers, und \'installiert CRM auch Zugangsdaten',
    'LBL_STEP1_OL_NAME' => 'Phase 1',
    'LBL_STEP2_DESC' => 'Herunterladen von Daten ... bitte warten ...',
    'LBL_STEP2_NAME' => 'Phase 2',
    'LBL_STEP2_OL_DESC' => 'Hochladen von Daten ... bitte warten ...',
    'LBL_STEP2_OL_NAME' => 'Phase 2',
    'LBL_STEP3_DESC' => 'Eingabe von Daten in den Offline-Client aktualisiert ...',
    'LBL_STEP3_NAME' => 'Phase 3',
    'LBL_STEP3_OL_DESC' => 'Einfügen von Datum Daten auf dem Server Online in progress ...',
    'LBL_STEP3_OL_NAME' => 'Phase 3',
    'LBL_STEPLAST_DESC' => 'Ab jetzt können Sie, um CRM-lokal, ohne Zugang zu den wichtigsten CRM zu arbeiten. Clips Klicken Sie auf Login, um CRM offline zugreifen!',
    'LBL_STEPLAST_NAME' => 'Verfahren erfolgreich durchgeführt!',
    'LBL_STEPLAST_OL_DESC' => 'Die Daten wurden erfolgreich in das Online-Server eingesetzt wird. Clips Klicken Sie auf Login, um CRM-Online-Zugang zu haben!',
    'LBL_STEPLAST_OL_NAME' => 'Verfahren erfolgreich durchgeführt!',
    'LBL_USER_NAME' => 'Benutzername',
    'Offline' => 'Offline',
    'SINGLE_Offline' => 'Offline',
  ),
  'PDFMaker' => 
  array (
    'LBL_ADD_FOLLOWING' => 'fügen Sie den folgenden',
    'LBL_AROUND_LINE' => 'Rund Linie',
    'LBL_BARCODES_TYPE3' => 'EAN-2 und EAN-5 ergänzt, und kombinierte Formen',
    'LBL_CREATE_RELATED_BLOCK' => 'Block erstellen',
    'LBL_CUSTOM' => 'Benutzerdefinierte',
    'LBL_CUSTOM_DESC' => 'Wenn einige Änderungen wurden in der obigen Datei Installations vtiger Standard.',
    'LBL_NEXT' => 'Vorwärts',
  ),
  'ProjectPlan' => 
  array (
    'projecturl' => 'Url Projekt',
  ),
  'Quotes' => 
  array (
    'Amount' => 'Wert',
    'Competitors' => 'Wettbewerber',
    'Contract duration' => 'Vertragslänge',
    'Expected Close Date' => 'Einsendeschluss angemeldet',
    'Level of interest' => 'Interesse',
    'Notice period' => 'Erscheinungszeitraum',
    'Opportunity source' => 'Origin Chance "',
    'Overall Quantity' => 'Menge \'Gesamt',
    'Probability' => 'Wahrscheinlichkeit',
    'Product line' => 'Product Line',
    'Reason' => 'Gründe für den Gewinn / Verlust',
    'Relationship' => 'Verwandtschaft',
    'Statistic group' => 'Gruppenstatistiken',
  ),
  'Settings' => 
  array (
    'LBL_EDIT_MODULE_SCRIPTS' => 'Skript bearbeiten Installations',
    'LBL_ENABLE_DUPCHECK' => 'Freigabe Steuerung Duplikate',
    'LBL_ENABLE_DUPCHECK_DESC' => '',
    'LBL_ENABLE_EXPORT' => 'Exporte zu ermöglichen',
    'LBL_ENABLE_EXPORT_DESC' => '',
    'LBL_ENABLE_IMPORT' => 'Aktivieren Importe',
    'LBL_ENABLE_IMPORT_DESC' => '',
    'LBL_ENABLE_QUICKCREATE' => 'Ermöglicht die schnelle Erstellung',
    'LBL_ENABLE_QUICKCREATE_DESC' => '',
    'LBL_ERROR_CREATING_INSTALL_SCRIPT' => 'Fehler beim Erstellen des Installationsskripts',
    'LBL_ERROR_LANGUAGE_RENAME' => 'Fehler beim Erstellen von Sprachdateien',
    'LBL_FIELD_AUTONUMBER' => 'Automatische Nummerierung',
    'LBL_FIELD_PROPERTIES' => 'Feldeigenschaften',
    'LBL_FIRST_MODULE_DESC' => 'Der erste Teil des Berichts',
    'LBL_FLAG_FOR_ALL_PROFILES' => 'Diese Option gilt für alle Profile. Sobald das Modul installiert ist, können Sie die Einstellungen ändern',
    'LBL_IMPORT_ERROR_NOTIF_DESC' => 'Überprüfen Sie die Protokolle importieren <a href="index.php?module=Settings&action=DataImporter"> </a> dieser Seite',
    'LBL_IMPORT_ERROR_SUBJECT' => 'Fehler Import Auto',
    'LBL_IMPORT_IS_ALREADY_RUNNING' => 'Der Import ist bereits in Arbeit',
    'LBL_IMPORT_LINKKEY_FIELD' => 'Link-Feld',
    'LBL_IMPORT_NO_LOCAL_INFILE' => 'Beim Import müssen Sie den Parameter local-infile = 1 in der Datei my.cnf-Server MySQL geben',
    'LBL_IMPORT_TABLE' => 'Quelltabelle',
    'LBL_INVALID_FILE_EXTENSION' => 'Dateierweiterung ist ungültig',
    'LBL_INVALID_MODULE' => 'Ungültige Modul',
    'LBL_INVALID_QUERY' => 'Die Abfrage ist ungültig',
    'LBL_INVALID_SOURCETYPE' => 'Art der Quellendaten ungültig',
    'LBL_INVENTORYMODULE' => 'Modul mit Blockprodukte',
    'LBL_INVENTORYMODULE_DESC' => 'Markieren Sie das Kästchen, wenn das Formular wird blockiert Produkte',
    'LBL_LAST_IMPORT' => 'Letzter Import',
    'LBL_LAST_IMPORT_LOG' => 'Letzter Import Bericht',
    'LBL_MAILCONNECTOR' => 'Mail Connector',
    'LBL_MAILCONNECTOR_DESCRIPTION' => 'Mail Connector',
    'LBL_MMAKER_CANT_DELETE_INSTALLED' => 'Sie können eine installierte Modul nicht entfernen',
    'LBL_MMAKER_ERR_SAMEMODULERELATED' => 'Das Modul %s ist in mehr als eine Beziehung vorhanden ist. Und \'möglich, nur einen Bericht für jedes Modul haben',
    'LBL_MMAKER_IMPORT_INTRO' => 'Wählen Sie die Datei, um das Modul importieren möchten. Einmal geladen können Sie die Einstellungen vor der Installation zu ändern.',
    'LBL_MMAKER_INSTALLING_MODULE' => 'Und "es installiert ist Modul. Dieser Vorgang kann einige Minuten dauern.',
    'LBL_MMAKER_INSTALLSCRIPT' => 'Script Installations',
    'LBL_MMAKER_INSTALL_ERROR' => 'Fehler bei der Installation. Überprüfen Sie die Protokolle für Details',
    'LBL_MMAKER_RELATED_FILTER' => 'Wählen Sie die Felder für die damit verbundenen Listen',
    'LBL_MMAKER_STEP1_INTRO' => 'Geben Sie die grundlegenden Informationen für das neue Modul',
    'LBL_MMAKER_STEP2_INTRO' => 'Hinzufügen oder Ändern von Feldern für das Modul',
    'LBL_MMAKER_STEP3_INTRO' => 'Konfigurieren Sie die Felder für den Standardfilter',
    'LBL_MMAKER_STEP4_INTRO' => '',
    'LBL_MMAKER_STEP5_INTRO' => 'Hier können Sie die Feldbezeichnungen ändern und Formensprache installiert',
    'LBL_MMAKER_STEP6_INTRO' => 'Erweiterte Optionen für das Modul',
    'LBL_MMAKER_UNINSTALLING_MODULE' => 'Und \'entfernt Modul. Warten.',
    'LBL_MMAKER_UNINSTALLSCRIPT' => 'Deinstallationsskript',
    'LBL_MMAKER_UNINSTALL_ERROR' => 'Fehler beim Entfernen. Überprüfen Sie die Protokolle für Details',
    'LBL_MOBILE_HANDLING' => 'Management Mobil',
    'LBL_MODULELABEL' => 'Label-Modul',
    'LBL_MODULELABEL_DESC' => 'Der Name des neuen Moduls',
    'LBL_MODULENAME' => 'Name Modul (automatisch)',
    'LBL_MODULENAME_DESC' => 'Der Modulname, intern verwendet. Dieses Feld wird automatisch berechnet',
    'LBL_MODULESINGLELABEL' => 'Etikettenform (Singular)',
    'LBL_MODULESINGLELABEL_DESC' => 'Das Etikett der Singularform, die einen einzelnen Datensatz identifiziert. Zum Beispiel, wenn Sie Ihr Formular wird als "Kosten", dieses Label könnte "Ausgaben" werden',
    'LBL_MODULE_ALREADY_INSTALLED' => 'Das Modul installiert ist',
    'LBL_MODULE_MAKER' => 'Formularerstellung',
    'LBL_MODULE_MAKER_DESC' => 'Es ermöglicht Ihnen, benutzerdefinierte Formulare erstellen',
    'LBL_MODULE_MAKER_STEP1' => 'Informationsformular',
    'LBL_MODULE_MAKER_STEP2' => 'Blöcke und Felder',
    'LBL_MODULE_MAKER_STEP3' => 'Standardfilter',
    'LBL_MODULE_MAKER_STEP4' => 'Beziehungen',
    'LBL_MODULE_MAKER_STEP5' => 'Labels',
    'LBL_MODULE_MAKER_STEP6' => 'Erweiterte',
    'LBL_NEXT_FLAGS_FOR_ALL_PROFILES' => 'Die folgenden Optionen werden auf alle Profile anwenden. Sobald das Modul installiert ist, können Sie die Einstellungen ändern',
    'LBL_NEXT_IMPORT_TIME' => 'Nächste Start',
    'LBL_NOT_ALLOWED_UPLOAD_SCRIPTS' => 'Sie sind nicht gestattet, Module mit benutzerdefinierten Skripts zu laden',
    'LBL_NO_CUSTOM_MODULES' => 'Keine benutzerdefinierten Formular, drücken Sie, um eine neue zu erstellen hinzufügen',
    'LBL_NO_DATA_IMPORTER' => 'Kein Import konfiguriert, drücken Sie, um eine neue zu erstellen hinzufügen',
    'LBL_NO_FIELDS_FOR_FILTER' => 'Kein Feld für den Filter ausgewählt',
    'LBL_NO_FIELDS_TO_MOVE_IN_BLOCK' => 'Es gibt Felder zur Verfügung, um in diesem Block zu bewegen',
    'LBL_NO_MATCHING_FILES' => 'Keine passende Datei gefunden',
    'LBL_NO_OTHER_RELATIONS_FOUND' => 'Kein vorliegenden Beziehung. Drücken Sie Hinzufügen, um eine neue zu erstellen.',
    'LBL_NO_QUERY_RESULT' => 'Die Abfrage nicht Ergebnisse zurück.',
    'LBL_NO_RELATIONS' => 'Keine Beziehung, drücken Sie, um eine zu erstellen hinzufügen',
    'LBL_NO_RELATIONS_FOUND' => 'Keine Verletzungen. Erstellen Sie einen Erfahrungsbericht in Schritt 2, oder drücken Sie Hinzufügen, um eine neue Beziehung erstellen.',
    'LBL_OR_WRITE_IMPORT_QUERY' => 'Alternativ schreiben Sie die Abfrage Import',
    'LBL_OTHER_RELATIONS' => 'Andere Berichte',
    'LBL_RECORD_IDENTIFIER' => 'Hauptfeld',
    'LBL_RECORD_IDENTIFIER_DESC' => 'Der Name des Hauptfeldes der Form, wie zum Beispiel "Vornamen Expense"',
    'LBL_RELATED_MODULES' => 'Verwandte Module',
    'LBL_RELATED_PRODUCTS' => 'Lock Produkte',
    'LBL_RELATIONS_NTO1' => ' Relations N 1, über ein Feld in dieser Form',
    'LBL_RELATION_BLOCK_DESC' => 'Der Block, auf dem das neue Feld Bericht zu erstellen',
    'LBL_RELATION_FIELD_DESC' => 'Der Name des neuen Feldes des ausgewählten Moduls',
    'LBL_RELATION_MODULE_DESC' => 'Das Modul gemeldet',
    'LBL_RELATION_TYPE' => 'Beziehungsart',
    'LBL_RELATION_TYPE_1TON' => '1 bis N',
    'LBL_RELATION_TYPE_DESC' => 'Wählen Sie den Typ des Berichts. 1 bis N bedeutet, dass jeder Eintrag in dieser Form mit mehreren Datensätzen der Zielmodul verbunden werden, wobei ein neues Feld in der letzteren. N N ermöglicht statt freie Verbindung.',
    'LBL_RELATION_TYPE_NTO1' => 'N 1',
    'LBL_RELATION_TYPE_NTON' => 'N N',
    'LBL_REPEAT_EVERY' => 'Wiederholen alle',
    'LBL_RESTORE_CHANGED_FILES' => 'Wiederherstellen von Dateien',
    'LBL_SEGRETARIA' => 'Secretary',
    'LBL_SELECT_FIELD_TO_MOVE_IN_BLOCK' => 'Wählen Sie die Felder, um in diesem Block zu bewegen',
    'LBL_SELECT_INSTALLATION_LOG' => 'Wählen Sie die Log-Datei die Sie sehen wollen',
    'LBL_START_EVERY' => 'Beginnen Sie jeden',
    'LBL_UNABLE_TO_CONNECT_TO_DB' => 'Kann nicht mit der Datenbank verbinden, überprüfen Sie die Verbindungsparameter',
    'LBL_USEREDIT_EDIT_CODE_DESC' => 'Einige Dateien wurden geändert, so dass Sie keine Änderungen an der Konfiguration des Moduls zu machen. Um das ursprüngliche Skript wiederherzustellen, drücken Riprstina Dateien',
    'LBL_VALUE_FORMAT' => 'Wert-Format',
    'Line Total' => 'Gesamtleitung',
    'LBL_ABORT_IMPORT' => 'Stoppen',
    'LBL_ADD_NEW_FIELD' => 'Feld hinzufügen',
    'LBL_ADD_NEW_RELATED_FIELD' => 'Erfahrungsbericht hinzufügen',
    'LBL_ALTER_QUERY_TO_GET_ROWS' => 'Ändern Sie die Abfrage oder die Quelltabelle, so dass Sie zumindest eine Reihe zu bekommen.',
    'LBL_AREA_DESC' => 'Der Bereich der Zugehörigkeit des Moduls (optional)',
    'LBL_ASSOCIATED_MODULE_DESC' => 'Wählen Sie das Modul, das die Blockprodukte importiert werden enthält. Es muss ein Modul bereits für den Import konfiguriert werden',
    'LBL_ASSOCIATED_MODULE_DESC_RO' => 'Das Modul, das die Blockprodukte importiert werden',
    'LBL_BUTTON_EDIT_SCRIPTS' => 'Öffnen Sie Editor',
    'LBL_CANT_DELETE_RUNNING_IMPORT' => 'Es ist nicht möglich, einen Importvorgang löschen',
    'LBL_CANT_DISABLE_RUNNING_IMPORT' => 'Es ist nicht möglich, einen Importvorgang deaktivieren',
    'LBL_CANT_IMPORT_PRODUCT_ROWS' => 'Sie können die Produktlinien nicht importiert werden, wenn sie nicht konfiguriert ist, um die Produkte zu importieren und einen Block mit den Produkten zu bilden',
    'LBL_CHOOSE_CSV_DESC' => 'Wählen Sie die Datei, die Sie importieren möchten. Wenn die Liste leer ist, laden Sie die Dateien im Datenimport /',
    'LBL_CHOOSE_CSV_TITLE' => 'Datei importieren',
    'LBL_CREATE_NEW_FIELD' => 'Feld hinzufügen',
    'LBL_CREATE_NEW_MODULE' => 'Neues Modul',
    'LBL_CSVPATH_MUST_BE_ABSOLUTE' => 'Der Pfad der CSV-Datei muss absolut sein',
    'LBL_CSVPATH_MUST_NOT_BE_ABSOLUTE' => 'Der Pfad der CSV-Datei kann nicht absolut sein',
    'LBL_DATA_IMPORTER' => 'Datenimport',
    'LBL_DATA_IMPORTER_DESC' => 'Konfigurieren Sie automatische Datenimport aus externen Quellen',
    'LBL_DATA_IMPORTER_STEP1' => 'Form',
    'LBL_DATA_IMPORTER_STEP2' => 'Quelldaten',
    'LBL_DATA_IMPORTER_STEP3' => 'Parameter source',
    'LBL_DATA_IMPORTER_STEP4' => 'Tabelle Quelle',
    'LBL_DATA_IMPORTER_STEP5' => 'Mapping Felder',
    'LBL_DATA_IMPORTER_STEP6' => 'Termine Start',
    'LBL_DATA_IMPORTER_STEP7' => 'Benachrichtigungen',
    'LBL_DEFAULT_FIELDS_CREATE' => 'Felder standardmäßig in der Schöpfung',
    'LBL_DEFAULT_FIELDS_UPDATE' => 'Standardfelder in Wechsel',
    'LBL_DIMPORT_CSVPATH' => 'CSV-Dateipfad',
    'LBL_DIMPORT_CSVPATH_DESC' => 'Der Pfad zu dem Verzeichnis dataimport file / CSV importiert werden, beispielsweise file.csv (Datenimport / file.csv). Der Name kann Platzhalterzeichen enthalten, wie * oder? um weitere Dateien enthalten. Für mehrere Dateien, muss die Codierung und die Struktur für alle gleich sein.',
    'LBL_DIMPORT_FORMAT_DATETIME' => 'Datum und Uhrzeit',
    'LBL_DIMPORT_FORMAT_EMAIL' => 'Format E-Mail',
    'LBL_DIMPORT_FORMAT_INTEGER_01' => 'Voll 0/1',
    'LBL_DIMPORT_FORMAT_INTEGER_NULL' => 'Wert leer / nicht leer',
    'LBL_DIMPORT_FORMAT_PHONE' => 'Format Telefonnummer',
    'LBL_DIMPORT_FORMULA_ADD' => 'Hinzufügen',
    'LBL_DIMPORT_FORMULA_APPEND' => 'Anhängen',
    'LBL_DIMPORT_FORMULA_PREPEND' => 'Vorsilbe',
    'LBL_DIMPORT_FORMULA_SUBTRACT' => 'Subtrahieren',
    'LBL_DIMPORT_FORMULA_YEAR' => 'Auszug Jahr',
    'LBL_DIMPORT_FORMULA_YEARMONTH' => 'Auszug Jahr und Monat',
    'LBL_DIMPORT_INV_ROWS_SQL_NOTE' => 'Hinweis: stellen Sie sicher, dass die Abfrage Extraktion werden die Linien der Produkte gemäß der Medienorganisation angeordnet',
    'LBL_DIMPORT_MODULE_DESC' => 'Wählen Sie die Zielform zu importierenden Daten',
    'LBL_DIMPORT_MODULE_DESC_RO' => 'Dieses Modul ist das Datenziel. Es ist nicht mehr bearbeitet',
    'LBL_DIMPORT_NOTIFYTO_DESC' => 'Die gewählte Person wird per E-Mail oder über Anmeldungen von VTE benachrichtigt werden, abhängig von den Benutzereinstellungen',
    'LBL_DIMPORT_STEP1_INTRO' => '',
    'LBL_DIMPORT_STEP2_INTRO' => 'Wählen Sie den Typ der Datenquelle',
    'LBL_DIMPORT_STEP3_INTRO' => 'Die Parameter der Verbindung mit der Datenquellenauswahl',
    'LBL_DIMPORT_STEP4_INTRO' => 'Wählen Sie die Quelltabelle, aus der die Daten importiert werden',
    'LBL_DIMPORT_STEP5_INTRO' => 'Legt die Mapping Felder für den Import. E \'können das Format für einige Datentypen zu wählen, und einfache Operationen auf sie',
    'LBL_DIMPORT_STEP6_INTRO' => 'Wenn Sie möchten, um dieses automatischen Import zu starten?',
    'LBL_DIMPORT_STEP7_INTRO' => 'Wählen Sie, welche Benutzerbenachrichtigungen über mögliche Fehler oder Fehlfunktionen Import senden',
    'LBL_DUPLICATE_FIELDS_FOR_FILTER' => 'Es gibt doppelte Felder in der Filter',
    'LBL_EDIT_EMAIL_TEMPLATES' => 'Bearbeiten E-Mail-Vorlage',
    'LBL_EDIT_FIELD_PROPERTY_DESC' => 'Wählen Sie die Optionen, um den gewählten Bereich ändern',
  ),
  'Users' => 
  array (
    'LBL_MAIL_LOCKED_LOGIN_BODY' => 'Hallo, sie sind mehr als %s Anmeldeversuche nicht korrekt mit Ihrem Publikum, indem Sie die IP-Adresse %s vorgenommen wurden.
<br /> Als Vorsichtsmaßnahme haben wir Zugang Benutzer von dieser Adresse blockiert.
<br />
<br /> Wenn Sie Kenntnis von diesen Fehlversuchen und würden den Zugang zu dieser IP Klicken Sie auf %s wieder herzustellen.
<br /> Wenn Sie keine Kenntnis von diesen Fehlversuchen sind, können Sie diese Meldung ignorieren und möglicherweise entsperren Zugang späteren Kontakt mit dem System-Administrator.
<br />
<br /> Grüße,
<br /> Leaders vtecrm',
    'LBL_MAIL_LOCKED_LOGIN_BODY_AS' => 'Hallo, wurden Versuche unternommen, um mehr mit Ihren Benutzern auf einem Active Sync-kompatibles Gerät durch die folgende IP-Adresse %s zugreifen falsche als%s Stunden.
<br /> Als Vorsichtsmaßnahme haben wir Zugang Benutzer von dieser Adresse blockiert.
<br />
<br /> Wenn Sie Kenntnis von diesen Fehlversuchen und würden den Zugang zu dieser IP Klicken Sie auf %s wieder herzustellen.
<br /> Wenn Sie keine Kenntnis von diesen Fehlversuchen sind, können Sie diese Meldung ignorieren und möglicherweise entsperren Zugang späteren Kontakt mit dem System-Administrator.
<br />
<br /> Grüße,
<br /> Leaders vtecrm',
    'LBL_MAIL_LOCKED_LOGIN_SUBJECT' => 'Wichtig zu verlockend, um den Zugriff gemacht',
  ),
  'com_vtiger_workflow' => 
  array (
    'LBL_METHOD_NAME' => 'Funktion',
    'LBL_NO_METHOD_AVAILABLE' => 'Keine Funktion für dieses Modul verfügbar',
  ),
);


// check if installed
$res = $adb->pquery("SELECT id FROM {$table_prefix}_language WHERE prefix = ?", array('de_de'));
if ($res && $adb->num_rows($res) == 1 && is_array($lang_add)) {
	foreach ($lang_add as $module=>$list) {
		foreach ($list as $label=>$trans) {
			SDK::setLanguageEntry($module, $language, $label, $trans);
		}
	}
}


?>