<?php
global $adb;
$adb->query("ALTER TABLE vtiger_accounttype     CHANGE accounttypeid accounttypeid INT(19) NOT NULL");
$adb->query("ALTER TABLE vtiger_activity_view     CHANGE activity_viewid activity_viewid INT(19) NOT NULL");
$adb->query("ALTER TABLE vtiger_activitytype     CHANGE activitytypeid activitytypeid INT(19) NOT NULL");
$adb->query("ALTER TABLE vtiger_campaignstatus     CHANGE campaignstatusid campaignstatusid INT(19) NOT NULL");
$adb->query("ALTER TABLE vtiger_campaigntype     CHANGE campaigntypeid campaigntypeid INT(19) NOT NULL");
$adb->query("ALTER TABLE vtiger_carrier     CHANGE carrierid carrierid INT(19) NOT NULL");
$adb->query("ALTER TABLE vtiger_contract_priority     CHANGE contract_priorityid contract_priorityid INT(11) NOT NULL");
$adb->query("ALTER TABLE vtiger_contract_status     CHANGE contract_statusid contract_statusid INT(11) NOT NULL");
$adb->query("ALTER TABLE vtiger_contract_type     CHANGE contract_typeid contract_typeid INT(11) NOT NULL");
$adb->query("ALTER TABLE vtiger_convertleadmapping     CHANGE cfmid cfmid INT(19) NOT NULL");
$adb->query("ALTER TABLE vtiger_currencies     CHANGE currencyid currencyid INT(19) NOT NULL");
$adb->query("ALTER TABLE vtiger_date_format     CHANGE date_formatid date_formatid INT(19) NOT NULL");
$adb->query("ALTER TABLE vtiger_def_org_share     CHANGE ruleid ruleid INT(11) NOT NULL");
$adb->query("ALTER TABLE vtiger_duration_minutes     CHANGE minutesid minutesid INT(19) NOT NULL");
$adb->query("ALTER TABLE vtiger_emailtemplates     CHANGE templateid templateid INT(19) NOT NULL");
$adb->query("ALTER TABLE vtiger_eventhandlers     CHANGE eventhandler_id eventhandler_id INT(11) NOT NULL");
$adb->query("ALTER TABLE vtiger_eventhandler_module     CHANGE eventhandler_module_id eventhandler_module_id INT(11) NOT NULL");
$adb->query("ALTER TABLE vtiger_eventstatus     CHANGE eventstatusid eventstatusid INT(19) NOT NULL");
$adb->query("ALTER TABLE vtiger_expectedresponse     CHANGE expectedresponseid expectedresponseid INT(19) NOT NULL");
$adb->query("ALTER TABLE vtiger_failtype     CHANGE failtypeid failtypeid INT(11) NOT NULL");
$adb->query("ALTER TABLE vtiger_faqcategories     CHANGE faqcategories_id faqcategories_id INT(19) NOT NULL");
$adb->query("ALTER TABLE vtiger_faqstatus     CHANGE faqstatus_id faqstatus_id INT(19) NOT NULL");
$adb->query("ALTER TABLE vtiger_field     CHANGE fieldid fieldid INT(19) NOT NULL");
$adb->query("ALTER TABLE vtiger_glacct     CHANGE glacctid glacctid INT(19) NOT NULL");
$adb->query("ALTER TABLE vtiger_industry     CHANGE industryid industryid INT(19) NOT NULL");
$adb->query("ALTER TABLE vtiger_insufficient_stock     CHANGE insufficient_stockid insufficient_stockid INT(19) NOT NULL");
$adb->query("ALTER TABLE vtiger_inventorynotification     CHANGE notificationid notificationid INT(19) NOT NULL");
$adb->query("ALTER TABLE vtiger_invoicestatus     CHANGE inovicestatusid inovicestatusid INT(19) NOT NULL");
$adb->query("ALTER TABLE vtiger_language     CHANGE id id INT(11) NOT NULL");
$adb->query("ALTER TABLE vtiger_lead_view     CHANGE lead_viewid lead_viewid INT(19) NOT NULL");
$adb->query("ALTER TABLE vtiger_leadsource     CHANGE leadsourceid leadsourceid INT(19) NOT NULL");
$adb->query("ALTER TABLE vtiger_leadstatus     CHANGE leadstatusid leadstatusid INT(19) NOT NULL");
$adb->query("ALTER TABLE vtiger_manufacturer     CHANGE manufacturerid manufacturerid INT(19) NOT NULL");
$adb->query("ALTER TABLE vtiger_memory_center     CHANGE memory_centerid memory_centerid INT(19) NOT NULL");
$adb->query("ALTER TABLE vtiger_notificationscheduler     CHANGE schedulednotificationid schedulednotificationid INT(19) NOT NULL");
$adb->query("ALTER TABLE vtiger_opportunity_type     CHANGE opptypeid opptypeid INT(19) NOT NULL");
$adb->query("ALTER TABLE vtiger_payment_duration     CHANGE payment_durationid payment_durationid INT(11) NOT NULL");
$adb->query("ALTER TABLE vtiger_postatus     CHANGE postatusid postatusid INT(19) NOT NULL");
$adb->query("ALTER TABLE vtiger_postatushistory     CHANGE historyid historyid INT(19) NOT NULL");
$adb->query("ALTER TABLE vtiger_product_lines     CHANGE product_linesid product_linesid INT(19) NOT NULL");
$adb->query("ALTER TABLE vtiger_productcategory     CHANGE productcategoryid productcategoryid INT(19) NOT NULL");
$adb->query("ALTER TABLE vtiger_projects_status     CHANGE projects_statusid projects_statusid INT(11) NOT NULL");
$adb->query("ALTER TABLE vtiger_quotestage     CHANGE quotestageid quotestageid INT(19) NOT NULL");
$adb->query("ALTER TABLE vtiger_rating     CHANGE rating_id rating_id INT(19) NOT NULL");
$adb->query("ALTER TABLE vtiger_recurring_frequency     CHANGE recurring_frequencyid recurring_frequencyid INT(11) NOT NULL");
$adb->query("ALTER TABLE vtiger_recurringtype     CHANGE recurringeventid recurringeventid INT(19) NOT NULL");
$adb->query("ALTER TABLE vtiger_reminder_interval     CHANGE reminder_intervalid reminder_intervalid INT(19) NOT NULL");
$adb->query("ALTER TABLE vtiger_sales_stage     CHANGE sales_stage_id sales_stage_id INT(19) NOT NULL");
$adb->query("ALTER TABLE vtiger_salutationtype     CHANGE salutationid salutationid INT(19) NOT NULL");
$adb->query("ALTER TABLE vtiger_service_usageunit     CHANGE service_usageunitid service_usageunitid INT(11) NOT NULL");
$adb->query("ALTER TABLE vtiger_servicecategory     CHANGE servicecategoryid servicecategoryid INT(11) NOT NULL");
$adb->query("ALTER TABLE vtiger_sostatus     CHANGE sostatusid sostatusid INT(19) NOT NULL");
$adb->query("ALTER TABLE vtiger_status     CHANGE statusid statusid INT(19) NOT NULL");
$adb->query("ALTER TABLE vtiger_taskpriority     CHANGE taskpriorityid taskpriorityid INT(19) NOT NULL");
$adb->query("ALTER TABLE vtiger_taskstatus     CHANGE taskstatusid taskstatusid INT(19) NOT NULL");
$adb->query("ALTER TABLE vtiger_taxclass     CHANGE taxclassid taxclassid INT(19) NOT NULL");
$adb->query("ALTER TABLE vtiger_ticketcategories     CHANGE ticketcategories_id ticketcategories_id INT(19) NOT NULL");
$adb->query("ALTER TABLE vtiger_ticketpriorities     CHANGE ticketpriorities_id ticketpriorities_id INT(19) NOT NULL");
$adb->query("ALTER TABLE vtiger_ticketseverities     CHANGE ticketseverities_id ticketseverities_id INT(19) NOT NULL");
$adb->query("ALTER TABLE vtiger_ticketstatus     CHANGE ticketstatus_id ticketstatus_id INT(19) NOT NULL");
$adb->query("ALTER TABLE vtiger_timecardtype     CHANGE timecardtypeid timecardtypeid INT(11) NOT NULL");
$adb->query("ALTER TABLE vtiger_tracking_unit     CHANGE tracking_unitid tracking_unitid INT(11) NOT NULL");
$adb->query("ALTER TABLE vtiger_usageunit     CHANGE usageunitid usageunitid INT(19) NOT NULL");
$adb->query("ALTER TABLE vtiger_version     CHANGE id id INT(11) NOT NULL");
$adb->query("ALTER TABLE vtiger_visibility     CHANGE visibilityid visibilityid INT(19) NOT NULL");
$adb->query("ALTER TABLE vtiger_ws_entity_fieldtype     CHANGE fieldtypeid fieldtypeid INT(19) NOT NULL");
$adb->query("ALTER TABLE vtiger_ws_entity     CHANGE id id INT(11) NOT NULL");
$adb->query("ALTER TABLE vtiger_ws_operation     CHANGE operationid operationid INT(11) NOT NULL");
$adb->query("ALTER TABLE vtiger_licencekeystatus     CHANGE licencekeystatusid licencekeystatusid INT(19) NOT NULL");
$adb->query("alter table vtiger_users change crypt_type crypt_type varchar(20) character set utf8 collate utf8_general_ci default 'BLOWFISH' NOT NULL");
$adb->query("RENAME TABLE com_vtiger_workflow_activatedonce TO com_vtiger_wf_activatedonce");
$adb->query("RENAME TABLE com_vtiger_workflowtasks_entitymethod TO com_vtiger_wft_entitymeth");
$adb->query("RENAME TABLE com_vtiger_workflowtasks_entitymethod_seq TO com_vtiger_wft_entitymeth_seq");
$adb->query("RENAME TABLE tbl_s_advancedrule_relmoduleslist TO tbl_s_advrule_relmoduleslist");
$adb->query("RENAME TABLE tbl_s_advancedrule_relmoduleslist_seq TO tbl_s_advrule_relmoduleslist_seq");
$adb->query("RENAME TABLE tbl_s_advancedrule_relmodules TO tbl_s_advrule_relmod");
$adb->query("RENAME TABLE tbl_s_advancedrule_relmodules_seq TO tbl_s_advrule_relmod_seq");
$adb->query("DROP TABLE vtiger_customfield_sequence_seq");
$adb->query("RENAME TABLE vtiger_datashare_module_rel TO vtiger_datashare_mod_rel");
$adb->query("RENAME TABLE vtiger_datashare_module_rel_seq TO vtiger_datashare_mod_rel_seq");
$adb->query("RENAME TABLE vtiger_datashare_relatedmodule_permission TO vtiger_datashare_relmod_perm");
$adb->query("RENAME TABLE vtiger_datashare_relatedmodules TO vtiger_datashare_relmodules");
$adb->query("RENAME TABLE vtiger_datashare_relatedmodules_seq TO vtiger_datashare_relmodules_seq");
$adb->query("RENAME TABLE vtiger_customfield_sequence_seq TO vtiger_customfield_seq");
$adb->query("UPDATE vtiger_customfield_seq SET id='1' WHERE id='85'");
$adb->query("RENAME TABLE vtiger_inventorynotification TO vtiger_inventorynotify");
$adb->query("RENAME TABLE vtiger_inventorynotification_seq TO vtiger_inventorynotify_seq");
$adb->query("RENAME TABLE vtiger_notificationscheduler TO vtiger_notifyscheduler");
$adb->query("RENAME TABLE vtiger_notificationscheduler_seq TO vtiger_notifyscheduler_seq");
$adb->query("RENAME TABLE vtiger_org_share_action_mapping TO vtiger_org_share_act_mapping");
$adb->query("RENAME TABLE vtiger_profile2globalpermissions TO vtiger_profile2globalperm");
$adb->query("RENAME TABLE vtiger_profile2standardpermissions TO vtiger_profile2standardperm");
$adb->query("RENAME TABLE vtiger_tmp_read_group_rel_sharing_per TO vtiger_tmp_read_g_rel_per");
$adb->query("RENAME TABLE vtiger_tmp_read_group_sharing_per TO vtiger_tmp_read_g_per");
$adb->query("RENAME TABLE vtiger_tmp_read_user_rel_sharing_per TO vtiger_tmp_read_u_rel_per");
$adb->query("RENAME TABLE vtiger_tmp_read_user_sharing_per TO vtiger_tmp_read_u_per");
$adb->query("RENAME TABLE vtiger_tmp_write_group_rel_sharing_per TO vtiger_tmp_write_g_rel_per");
$adb->query("RENAME TABLE vtiger_tmp_write_group_sharing_per TO vtiger_tmp_write_g_per");
$adb->query("RENAME TABLE vtiger_tmp_write_user_rel_sharing_per TO vtiger_tmp_write_u_rel_per");
$adb->query("RENAME TABLE vtiger_tmp_write_user_sharing_per TO vtiger_tmp_write_u_per");
$adb->query("RENAME TABLE tbl_s_advrule_relmoduleslist TO tbl_s_advrule_relmodlist");
$adb->query("RENAME TABLE tbl_s_advrule_relmoduleslist_seq TO tbl_s_advrule_relmodlist_seq");
$adb->query("RENAME TABLE vtiger_datashare_relmodules TO .vtiger_datashare_relmod");
$adb->query("RENAME TABLE vtiger_datashare_relmodules_seq TO .vtiger_datashare_relmod_seq");
$adb->query("RENAME TABLE vtiger_activity_reminder_popup TO .vtiger_act_reminder_popup");
$adb->query("RENAME TABLE vtiger_activity_reminder_popup_seq TO .vtiger_act_reminder_popup_seq");
$adb->query("ALTER TABLE vtiger_campaignaccrel     ADD COLUMN campaignrelstatusid INT(19) NOT NULL AFTER accountid,    DROP PRIMARY KEY,     ADD PRIMARY KEY(campaignid, accountid)");
$adb->query("RENAME TABLE vtiger_campaignaccrel TO vtiger_campaignaccountrel");
//crmv@18160
$_SESSION['modules_to_install']['Sms'] = 'packages/vte/mandatory/Sms.zip';
$_SESSION['modules_to_install']['Fax'] = 'packages/vte/mandatory/Fax.zip';
//crmv@18160 end
?>