<?php
$new_en_us_translations = array(
	array('module'=>'Accounts','label'=>'LBL_MEMBER_ORG_FORM_TITLE','trans_label'=>'Member organisations'),
	array('module'=>'Accounts','label'=>'LBL_WEBSITE','trans_label'=>'Web site'),
	array('module'=>'Accounts','label'=>'LBL_OTHER_PHONE','trans_label'=>'Phone (other)'),
	array('module'=>'Accounts','label'=>'LBL_ANY_PHONE','trans_label'=>'Phone (other):'),
	array('module'=>'Accounts','label'=>'LBL_OTHER_EMAIL_ADDRESS','trans_label'=>'email (other)'),
	array('module'=>'Accounts','label'=>'LBL_ANY_EMAIL','trans_label'=>'email (other):'),
	array('module'=>'Accounts','label'=>'LBL_ANY_ADDRESS','trans_label'=>'Address (other):'),
	array('module'=>'Accounts','label'=>'NTC_REMOVE_MEMBER_ORG_CONFIRMATION','trans_label'=>'Are you sure you want to remove this record as a member organisation?'),
	array('module'=>'Accounts','label'=>'ERR_DELETE_RECORD','trans_label'=>'Please select a record number to delete the vtiger_account.'),
	array('module'=>'Accounts','label'=>'Other Phone','trans_label'=>'Phone (other)'),
	array('module'=>'Accounts','label'=>'Other Email','trans_label'=>'email (other)'),
	array('module'=>'Accounts','label'=>'Created Time','trans_label'=>'Time created'),
	array('module'=>'Accounts','label'=>'Modified Time','trans_label'=>'Time modified'),
	array('module'=>'Accounts','label'=>'Not For Profit','trans_label'=>'Non-profit'),
	array('module'=>'Accounts','label'=>'LBL_EXPORT_RESULTS_EMAIL','trans_label'=>'Export emailer data'),
	array('module'=>'Accounts','label'=>'LBL_EXPORT_RESULTS_FULL','trans_label'=>'Export data including Contacts, email, Account name, Address, Telephone, etc.'),
	array('module'=>'Accounts','label'=>'LBL_INSERT_ENTRIE','trans_label'=>'as a new account'),
	array('module'=>'Calendar','label'=>'LBL_HOLDFOLLOWUP','trans_label'=>'Hold follow-up on'),
	array('module'=>'Calendar','label'=>'LBL_CHANGE_APPNT','trans_label'=>'View or change this appointment (%s - %s)'),
	array('module'=>'Calendar','label'=>'LBL_APP_IGNORE_TIME2','trans_label'=>'(i.e. the appointment takes place<br />at no fixed time on these day(s) )'),
	array('module'=>'Calendar','label'=>'LBL_APP_ERR004','trans_label'=>'No subject!'),
	array('module'=>'Calendar','label'=>'ERR_DELETE_RECORD','trans_label'=>'Please select a record number to delete the vtiger_account.'),
	array('module'=>'Calendar','label'=>'LBL_PUBLIC','trans_label'=>'Mark as Public'),
	array('module'=>'Calendar','label'=>'LBL_CALSHAREMESSAGE','trans_label'=>'Share my calendar with the following users'),
	array('module'=>'Calendar','label'=>'LBL_REPEAT_ONCE','trans_label'=>'Repeat once every'),
	array('module'=>'Calendar','label'=>'LBL_COMPLETED','trans_label'=>'Mark as Completed'),
	array('module'=>'Calendar','label'=>'LBL_HELD','trans_label'=>'Mark as Held'),
	array('module'=>'Calendar','label'=>'LBL_NOTHELD','trans_label'=>'Mark as Not Held'),
	array('module'=>'Calendar','label'=>'Created Time','trans_label'=>'Time created'),
	array('module'=>'Calendar','label'=>'LBL_NOTIFICATION_ERROR','trans_label'=>'Mail Error : Please check your outgoing mail server configuration in Settings->Outgoing Mail Server Configuration OR this user has no e-mail address'),
	array('module'=>'Calendar','label'=>'LBL_REPEATEVENT','trans_label'=>'Repeat once every'),
	array('module'=>'Calendar','label'=>'LBL_HR','trans_label'=>'Hr.'),
	array('module'=>'Calendar','label'=>'createdtime','trans_label'=>'Time created'),
	array('module'=>'Calendar','label'=>'LBL_ALL_EVENTS_TODOS','trans_label'=>'All Events & To-do\'s'),
	array('module'=>'Calendar','label'=>'LBL_REMAINDER_HRS','trans_label'=>'hrs.'),
	array('module'=>'Calendar','label'=>'End date','trans_label'=>'End Date'),
	array('module'=>'Calendar','label'=>'SHARED_EVENT_DEL_MSG','trans_label'=>'The User has no permission to Edit/Delete Shared Event.'),
	array('module'=>'Calendar','label'=>'NO_SUBJECT_SPECIFIED','trans_label'=>'Subject field is empty. Do you want to continue?'),
	array('module'=>'Calendar','label'=>'LBL_SKIPPED_CALENDAR_1','trans_label'=>'No. of Tasks Skipped that miss one or more required fields : '),
	array('module'=>'Calendar','label'=>'LBL_SKIPPED_EVENTS_1','trans_label'=>'No. of Events Skipped that miss one or more required fields : '),
	array('module'=>'Calendar','label'=>'LBL_CHANGE_ANSWER','trans_label'=>'If you want  change the answer click'),
	array('module'=>'Campaigns','label'=>'Created Time','trans_label'=>'Time created'),
	array('module'=>'Campaigns','label'=>'Actual Response Count','trans_label'=>'Actual number of responses'),
	array('module'=>'Campaigns','label'=>'Contacted - Successful','trans_label'=>'Contacted - Successfully'),
	array('module'=>'Campaigns','label'=>'Contacted - Unsuccessful','trans_label'=>'Contacted - Unsuccessfully'),
	array('module'=>'Contacts','label'=>'LBL_ANY_PHONE','trans_label'=>'Phone (other):'),
	array('module'=>'Contacts','label'=>'LBL_BIRTHDATE','trans_label'=>'Date of birth'),
	array('module'=>'Contacts','label'=>'LBL_ANY_EMAIL','trans_label'=>'email (other):'),
	array('module'=>'Contacts','label'=>'LBL_ANY_ADDRESS','trans_label'=>'Address (other):'),
	array('module'=>'Contacts','label'=>'NTC_COPY_PRIMARY_ADDRESS','trans_label'=>'Copy primary address to alternative address'),
	array('module'=>'Contacts','label'=>'NTC_COPY_ALTERNATE_ADDRESS','trans_label'=>'Copy alternative address to primary address'),
	array('module'=>'Contacts','label'=>'Birthdate','trans_label'=>'Date of birth'),
	array('module'=>'Contacts','label'=>'Created Time','trans_label'=>'Time created'),
	array('module'=>'Contacts','label'=>'LBL_WEBSITE','trans_label'=>'Web site'),
	array('module'=>'Contacts','label'=>'LBL_MAXIMUM_LIMIT_ERROR','trans_label'=>'Sorry, the uploaded file exceeds the maximum vtiger_filesize. Please try a file smaller than 800000 bytes'),
	array('module'=>'Contacts','label'=>'LBL_INVALID_IMAGE','trans_label'=>'invalid file OR File is empty'),
	array('module'=>'Contacts','label'=>'Web Site','trans_label'=>'Web site'),
	array('module'=>'Contacts','label'=>'We suggest you to change your password after logging in first time','trans_label'=>'Please change your password after first login.'),
	array('module'=>'Dashboard','label'=>'LBL_LEAD_SOURCE_FORM_DESC','trans_label'=>'Shows the cumulative amounts of opportunities per lead source of selected users.'),
	array('module'=>'Dashboard','label'=>'LBL_LEAD_SOURCE_BY_OUTCOME','trans_label'=>'All Opportunities By Lead Source and Outcome'),
	array('module'=>'Dashboard','label'=>'ERR_NO_OPPS','trans_label'=>'Please create some Opportunities to see the Opportunity graphs.'),
	array('module'=>'Dashboard','label'=>'LBL_OPPS_IN_STAGE','trans_label'=>'opportunities with sales stage'),
	array('module'=>'Dashboard','label'=>'LBL_OPPS_IN_LEAD_SOURCE','trans_label'=>'opportunities with lead source'),
	array('module'=>'Dashboard','label'=>'LBL_OPPS_OUTCOME','trans_label'=>'opportunities with outcome'),
	array('module'=>'Dashboard','label'=>'LBL_DATE_START','trans_label'=>'Start Date:'),
	array('module'=>'Dashboard','label'=>'LBL_NO_PERMISSION','trans_label'=>'Sorry, you do not have the access rights to this function'),
	array('module'=>'Dashboard','label'=>'LBL_NO_PERMISSION_FIELD','trans_label'=>'Sorry, you do not have the access rights to this function'),
	array('module'=>'Dashboard','label'=>'Not For Profit','trans_label'=>'Non-profit'),
	array('module'=>'Documents','label'=>'ERR_DELETE_RECORD','trans_label'=>'Please select a record number to delete the vtiger_account.'),
	array('module'=>'Documents','label'=>'Created Time','trans_label'=>'Time created'),
	array('module'=>'Documents','label'=>'FILE_HAS_NO_DATA','trans_label'=>'The selected file has no data or is invalid'),
	array('module'=>'Emails','label'=>'ERR_DELETE_RECORD','trans_label'=>'Please select a record number to delete the vtiger_account.'),
	array('module'=>'Emails','label'=>'LBL_DETAILVIEW_EMAIL','trans_label'=>'email'),
	array('module'=>'Emails','label'=>'NTC_REMOVE_INVITEE','trans_label'=>'Are you sure you want to remove this recipient?'),
	array('module'=>'Emails','label'=>'Sales Enity Module','trans_label'=>'Sales Entity Module'),
	array('module'=>'Emails','label'=>'Created Time','trans_label'=>'Time created'),
	array('module'=>'Emails','label'=>'MESSAGE_MAIL_ID_IS_INCORRECT','trans_label'=>'Mail address is incorrect. Please Check this Mail address...'),
	array('module'=>'Emails','label'=>'MESSAGE_CONTACT_NOT_WANT_MAIL','trans_label'=>'This Contact does not want to receive emails.'),
	array('module'=>'Emails','label'=>'LBL_MAIL_CONNECT_ERROR_INFO','trans_label'=>'Error connecting mail server!<br> Check in My Accounts->List Mail Server -> List e-mail account'),
	array('module'=>'Emails','label'=>'LBL_ALLMAILS','trans_label'=>'All emails'),
	array('module'=>'Emails','label'=>'SELECT_EMAIL','trans_label'=>'Select email addresses'),
	array('module'=>'Emails','label'=>'LBL_MAILSELECT_INFO1','trans_label'=>'The following email address types are associated to the selected'),
	array('module'=>'Emails','label'=>'LBL_MAILSELECT_INFO2','trans_label'=>'Select the email address types to which, the email should be sent'),
	array('module'=>'Emails','label'=>'LBL_COMPOSE_EMAIL','trans_label'=>'Compose email'),
	array('module'=>'Emails','label'=>'MESSAGE_MAIL_COULD_NOT_BE_SEND','trans_label'=>'Mail could not be sent to the assigned user.'),
	array('module'=>'Emails','label'=>'MESSAGE_PLEASE_CHECK_ASSIGNED_USER_EMAILID','trans_label'=>'Please check the user\'s email address.'),
	array('module'=>'Emails','label'=>'MESSAGE_PLEASE_CHECK_THE_FROM_MAILID','trans_label'=>'Please check the email address of'),
	array('module'=>'Emails','label'=>'MESSAGE_MAIL_COULD_NOT_BE_SEND_TO_THIS_EMAILID','trans_label'=>'Mail could not be sent to this email address'),
	array('module'=>'Emails','label'=>'PLEASE_CHECK_THIS_EMAILID','trans_label'=>'Please check this email address...'),
	array('module'=>'Emails','label'=>'LBL_CC_EMAIL_ERROR','trans_label'=>'Your cc mail address is invalid'),
	array('module'=>'Emails','label'=>'LBL_BCC_EMAIL_ERROR','trans_label'=>'Your bcc mail address is invalid'),
	array('module'=>'Emails','label'=>'LBL_NO_RCPTS_EMAIL_ERROR','trans_label'=>'No recipients specified'),
	array('module'=>'Emails','label'=>'LBL_MAILSELECT_INFO3','trans_label'=>'You are not authorised to view email address(s) of the selected Record(s).'),
	array('module'=>'Emails','label'=>'FEATURE_AVAILABLE_INFO','trans_label'=>'This feature is currently only available for Microsoft Internet Explorer 5.5+ users\n\nWait for an update!'),
	array('module'=>'Emails','label'=>'LBL_PLEASE_ATTACH','trans_label'=>'Please select a valid file to attach and try again!'),
	array('module'=>'Emails','label'=>'LBL_EXCEED_MAX','trans_label'=>'Sorry, the uploaded file exceeds the maximum file size. Please try a file smaller than '),
	array('module'=>'Emails','label'=>'LBL_CHECK_USER_MAILID','trans_label'=>'Please check the current user\'s email address'),
	array('module'=>'Emails','label'=>'LBL_MAILSELECT_INFO','trans_label'=>'has the following email addresses associated .Please Select the email addresses to which, the mail should be sent'),
	array('module'=>'Emails','label'=>'MESSAGE_NO_SUBJECT','trans_label'=>'Subject field is empty. Do you want to continue?'),
	array('module'=>'Emails','label'=>'Draft error','trans_label'=>'Unable to save in drafts. Check the webmail settings.'),
	array('module'=>'Faq','label'=>'LBL_MEMBER_ORG_FORM_TITLE','trans_label'=>'Member organisations'),
	array('module'=>'Faq','label'=>'LBL_WEBSITE','trans_label'=>'Web site'),
	array('module'=>'Faq','label'=>'LBL_ANY_PHONE','trans_label'=>'Phone (other):'),
	array('module'=>'Faq','label'=>'LBL_ANY_EMAIL','trans_label'=>'email (other):'),
	array('module'=>'Faq','label'=>'LBL_ANY_ADDRESS','trans_label'=>'Address (other):'),
	array('module'=>'Faq','label'=>'NTC_REMOVE_MEMBER_ORG_CONFIRMATION','trans_label'=>'Are you sure you want to remove this record as a member organisation?'),
	array('module'=>'Faq','label'=>'ERR_DELETE_RECORD','trans_label'=>'Please select a record number to delete the vtiger_account.'),
	array('module'=>'Faq','label'=>'Created Time','trans_label'=>'Time created'),
	array('module'=>'HelpDesk','label'=>'LBL_OPPURTUNITY','trans_label'=>'Opportunity'),
	array('module'=>'HelpDesk','label'=>'LBL_ESTIMATED_FINISHING_TIME','trans_label'=>'Estimated end Time'),
	array('module'=>'HelpDesk','label'=>'Created Time','trans_label'=>'Time created'),
	array('module'=>'HelpDesk','label'=>'link','trans_label'=>'You can use the following link to view the responses:'),
	array('module'=>'HelpDesk','label'=>'LBL_RESPOND','trans_label'=>'Please respond to above ticket as soon as possible.'),
	array('module'=>'HelpDesk','label'=>'LBL_LOGIN_DETAILS','trans_label'=>'These are your Customer Portal login details :'),
	array('module'=>'HelpDesk','label'=>'LBL_GIVE_MAILID','trans_label'=>'Please enter your email address'),
	array('module'=>'HelpDesk','label'=>'LBL_CHECK_MAILID','trans_label'=>'Please check your email address for the Customer Portal'),
	array('module'=>'HelpDesk','label'=>'LBL_LOGIN_REVOKED','trans_label'=>'Your login is no longer valid. Please contact your admin.'),
	array('module'=>'HelpDesk','label'=>'LBL_MAIL_SENT','trans_label'=>'Mail has been sent to your email address with the customer portal login details'),
	array('module'=>'HelpDesk','label'=>'LBL_ALTBODY','trans_label'=>'This is the body text for non-HTML mail clients'),
	array('module'=>'HelpDesk','label'=>'LBL_NewState','trans_label'=>'Change ticket status to'),
	array('module'=>'HelpDesk','label'=>'FinishDate','trans_label'=>'End date'),
	array('module'=>'HelpDesk','label'=>'sortSeeWO','trans_label'=>'View Work orders'),
	array('module'=>'HelpDesk','label'=>'LBL_HELPINFO_HOURS','trans_label'=>'Estimated number of days for the Ticket.<br>When this ticket is added to a Service Contract, the tracking unit of the Contract updates the units used when a ticket is Closed.'),
	array('module'=>'HelpDesk','label'=>'LBL_HELPINFO_DAYS','trans_label'=>'Estimated number of days for the Ticket.<br>When this ticket is added to a Service Contract, the tracking unit of the Contract updates the units used when a ticket is Closed.'),
	array('module'=>'Invoice','label'=>'LBL_MEMBER_ORG_FORM_TITLE','trans_label'=>'Member organisations'),
	array('module'=>'Invoice','label'=>'LBL_WEBSITE','trans_label'=>'Web site'),
	array('module'=>'Invoice','label'=>'LBL_ANY_PHONE','trans_label'=>'Phone (other):'),
	array('module'=>'Invoice','label'=>'LBL_ANY_EMAIL','trans_label'=>'email (other):'),
	array('module'=>'Invoice','label'=>'LBL_ANY_ADDRESS','trans_label'=>'Address (other):'),
	array('module'=>'Invoice','label'=>'NTC_REMOVE_MEMBER_ORG_CONFIRMATION','trans_label'=>'Are you sure you want to remove this record as a member organisation?'),
	array('module'=>'Invoice','label'=>'ERR_DELETE_RECORD','trans_label'=>'Please select a record number to delete the vtiger_account.'),
	array('module'=>'Invoice','label'=>'Created Time','trans_label'=>'Time created'),
	array('module'=>'Invoice','label'=>'Discount Percent','trans_label'=>'Discount Percentage'),
	array('module'=>'Leads','label'=>'LBL_WEBSITE','trans_label'=>'Web site'),
	array('module'=>'Leads','label'=>'NTC_COPY_PRIMARY_ADDRESS','trans_label'=>'Copy primary address to alternative address'),
	array('module'=>'Leads','label'=>'NTC_COPY_ALTERNATE_ADDRESS','trans_label'=>'Copy alternative address to primary address'),
	array('module'=>'Leads','label'=>'LBL_KINDLY_PROVIDE_AN_XLS_FILE','trans_label'=>'Please only use .xls files as input.'),
	array('module'=>'Leads','label'=>'LBL_PROVIDE_ATLEAST_ONE_FILE','trans_label'=>'Please select at least one file'),
	array('module'=>'Leads','label'=>'LBL_SELECT_TEMPLATE_TO_MAIL_MERGE','trans_label'=>'Select template for Mail Merge:'),
	array('module'=>'Leads','label'=>'Created Time','trans_label'=>'Time created'),
	array('module'=>'Leads','label'=>'Not For Profit','trans_label'=>'Non-profit'),
	array('module'=>'Leads','label'=>'Web Site','trans_label'=>'Web site'),
	array('module'=>'Leads','label'=>'LBL_FOLLOWING_ARE_POSSIBLE_REASONS','trans_label'=>'This can be be one of the possible reasons'),
	array('module'=>'Leads','label'=>'LBL_LEADS_FIELD_MAPPING_INCOMPLETE','trans_label'=>'The mandatory fields are not mapped'),
	array('module'=>'Potentials','label'=>'ERR_DELETE_RECORD','trans_label'=>'Please select a record number to delete the opportunity.'),
	array('module'=>'Potentials','label'=>'Created Time','trans_label'=>'Time created'),
	array('module'=>'PriceBooks','label'=>'Created Time','trans_label'=>'Time created'),
	array('module'=>'Products','label'=>'Created Time','trans_label'=>'Time created'),
	array('module'=>'Products','label'=>'LBL_MAXIMUM_LIMIT_ERROR','trans_label'=>'Sorry, the uploaded file exceeds the maximum vtiger_filesize. Please try a file smaller than 800000 bytes'),
	array('module'=>'Products','label'=>'LBL_INVALID_IMAGE','trans_label'=>'invalid file OR File is empty'),
	array('module'=>'Products','label'=>'307-Service-Hardware Labor','trans_label'=>'307-Service-Hardware Labour'),
	array('module'=>'Products','label'=>'MSG_PROCURE_REQUIRED_NUMBER','trans_label'=>'Stock level is below the set minimum, please order the required quantity.'),
	array('module'=>'PurchaseOrder','label'=>'LBL_MEMBER_ORG_FORM_TITLE','trans_label'=>'Member organisations'),
	array('module'=>'PurchaseOrder','label'=>'LBL_WEBSITE','trans_label'=>'Web site'),
	array('module'=>'PurchaseOrder','label'=>'LBL_ANY_PHONE','trans_label'=>'Phone (other):'),
	array('module'=>'PurchaseOrder','label'=>'LBL_ANY_EMAIL','trans_label'=>'email (other):'),
	array('module'=>'PurchaseOrder','label'=>'LBL_ANY_ADDRESS','trans_label'=>'Address (other):'),
	array('module'=>'PurchaseOrder','label'=>'NTC_REMOVE_MEMBER_ORG_CONFIRMATION','trans_label'=>'Are you sure you want to remove this record as a member organisation?'),
	array('module'=>'PurchaseOrder','label'=>'ERR_DELETE_RECORD','trans_label'=>'Please select a record number to delete the vtiger_account.'),
	array('module'=>'PurchaseOrder','label'=>'Created Time','trans_label'=>'Time created'),
	array('module'=>'PurchaseOrder','label'=>'Discount Percent','trans_label'=>'Discount Percentage'),
	array('module'=>'PurchaseOrder','label'=>'Comments','trans_label'=>'Comments'),
	array('module'=>'Quotes','label'=>'LBL_MEMBER_ORG_FORM_TITLE','trans_label'=>'Member organisations'),
	array('module'=>'Quotes','label'=>'LBL_WEBSITE','trans_label'=>'Web site'),
	array('module'=>'Quotes','label'=>'LBL_ANY_PHONE','trans_label'=>'Phone (other):'),
	array('module'=>'Quotes','label'=>'LBL_ANY_EMAIL','trans_label'=>'email (other):'),
	array('module'=>'Quotes','label'=>'LBL_ANY_ADDRESS','trans_label'=>'Address (other):'),
	array('module'=>'Quotes','label'=>'NTC_REMOVE_MEMBER_ORG_CONFIRMATION','trans_label'=>'Are you sure you want to remove this record as a member organisation?'),
	array('module'=>'Quotes','label'=>'ERR_DELETE_RECORD','trans_label'=>'Please select a record number to delete the vtiger_account.'),
	array('module'=>'Quotes','label'=>'Created Time','trans_label'=>'Time created'),
	array('module'=>'Quotes','label'=>'LBL_QUOTE_INFORMATION','trans_label'=>'Account Information'),
	array('module'=>'Quotes','label'=>'Discount Percent','trans_label'=>'Discount Percentage'),
	array('module'=>'Quotes','label'=>'Comments','trans_label'=>'Comments'),
	array('module'=>'Reports','label'=>'LBL_NEW_REP0_HDR1','trans_label'=>'Select a Module from which to create a new Report'),
	array('module'=>'Reports','label'=>'LBL_NEW_REP0_HDR4','trans_label'=>'Report Module and related module cannot be modified once selected.'),
	array('module'=>'Reports','label'=>'LBL_SPECIFY_CRITERIA','trans_label'=>'Specify the Criteria'),
	array('module'=>'Reports','label'=>'LBL_REPORT_TYPE_HDR1','trans_label'=>'Tabular Reports are an easy and fast way to show your data'),
	array('module'=>'Reports','label'=>'LBL_REPORT_TYPE_HDR2','trans_label'=>'Summary reports shows your data with subtotals and other summary information'),
	array('module'=>'Reports','label'=>'LBL_GROUPING_SUMMARIZE','trans_label'=>'Summarise information by:'),
	array('module'=>'Reports','label'=>'LBL_AF_HDR1','trans_label'=>'Set the search conditions to further shorten the list.'),
	array('module'=>'Reports','label'=>'LBL_NO_PERMISSION','trans_label'=>'Your profile does not allow you view the reports for one of the  module(s)'),
	array('module'=>'Reports','label'=>'LBL_TO_ADD_NEW_GROUP','trans_label'=>'to add a new folder'),
	array('module'=>'Reports','label'=>'LBL_DESCRIPTION_FOR_REPORT','trans_label'=>'Description of the report'),
	array('module'=>'Reports','label'=>'LBL_TABULAR_REPORTS_ARE_SIMPLEST','trans_label'=>'Tabular Reports are an easy and fast way to show your data'),
	array('module'=>'Reports','label'=>'LBL_SUMMARY_REPORT_VIEW_DATA_WITH_SUBTOTALS','trans_label'=>'Summary reports shows your data with subtotals and other summary information'),
	array('module'=>'Reports','label'=>'Open Tickets','trans_label'=>'Open tickets'),
	array('module'=>'Reports','label'=>'Tickets that are Open','trans_label'=>'Open tickets'),
	array('module'=>'Reports','label'=>'Campaign Expectations and Actuals','trans_label'=>'Campaign Expectations and Actuals (Forecast)'),
	array('module'=>'Reports','label'=>'LBL_REPORT_DELETED','trans_label'=>'The record has been deleted.'),
	array('module'=>'Reports','label'=>'CREATE_PROJECT_WORKER_REPORT','trans_label'=>'Utilisation report'),
	array('module'=>'Reports','label'=>'LBL_REPORT_PROJECT_EORKER_TO','trans_label'=>'Utilisation report for'),
	array('module'=>'Reports','label'=>'LBL_NewState','trans_label'=>'Change ticket status to'),
	array('module'=>'Reports','label'=>'LBL NewState','trans_label'=>'Change ticket status to'),
	array('module'=>'Reports','label'=>'LBL_FLDR_NOT_EMPTY','trans_label'=>'The folder you are trying to delete is not empty, Move or Delete the files in the folder first.'),
	array('module'=>'Rss','label'=>'LBL_ERROR_MSG','trans_label'=>'No RSS Feeds are selected or Your Proxy Settings are not correct'),
	array('module'=>'Rss','label'=>'NOT_A_VALID','trans_label'=>'Invalid RSS Feed or Your Proxy Settings is not correct'),
	array('module'=>'Rss','label'=>'INVALID_RSS_URL','trans_label'=>'Invalid RSS URL'),
	array('module'=>'SalesOrder','label'=>'LBL_MEMBER_ORG_FORM_TITLE','trans_label'=>'Member organisations'),
	array('module'=>'SalesOrder','label'=>'LBL_WEBSITE','trans_label'=>'Web site'),
	array('module'=>'SalesOrder','label'=>'LBL_ANY_PHONE','trans_label'=>'Phone (other):'),
	array('module'=>'SalesOrder','label'=>'LBL_ANY_EMAIL','trans_label'=>'email (other):'),
	array('module'=>'SalesOrder','label'=>'LBL_ANY_ADDRESS','trans_label'=>'Address (other):'),
	array('module'=>'SalesOrder','label'=>'NTC_REMOVE_MEMBER_ORG_CONFIRMATION','trans_label'=>'Are you sure you want to remove this record as a member organisation?'),
	array('module'=>'SalesOrder','label'=>'ERR_DELETE_RECORD','trans_label'=>'Please select a record number to delete the vtiger_account.'),
	array('module'=>'SalesOrder','label'=>'Created Time','trans_label'=>'Time created'),
	array('module'=>'SalesOrder','label'=>'Discount Percent','trans_label'=>'Discount Percentage'),
	array('module'=>'SalesOrder','label'=>'introduction','trans_label'=>'Introduction'),
	array('module'=>'SalesOrder','label'=>'Err_ContactWithoutAccount','trans_label'=>'No account associated to this contact. Please select an account.'),
	array('module'=>'SalesOrder','label'=>'Comments','trans_label'=>'Comments'),
	array('module'=>'Update','label'=>'LBL_UPDATE_PACK_INVALID','trans_label'=>'This update is not supported by your VTE version.<br />Please contact CRMVillage.BIZ or your Partner for the right version.'),
	array('module'=>'Users','label'=>'LBL_LIST_EMAIL','trans_label'=>'email'),
	array('module'=>'Users','label'=>'LBL_ANY_PHONE','trans_label'=>'Phone (other):'),
	array('module'=>'Users','label'=>'LBL_ANY_EMAIL','trans_label'=>'email (other):'),
	array('module'=>'Users','label'=>'LBL_EMAIL','trans_label'=>'email address'),
	array('module'=>'Users','label'=>'ERR_PASSWORD_INCORRECT_OLD','trans_label'=>'Incorrect or old password. Please re-enter your password.'),
	array('module'=>'Users','label'=>'ERR_USER_NAME_EXISTS_2','trans_label'=>' User name already exists. Please use another username'),
	array('module'=>'Users','label'=>'ERR_LAST_ADMIN_2','trans_label'=>' is the last Admin user.  At least one user must be an Admin user.<br>Check the Admin user settings.'),
	array('module'=>'Users','label'=>'ERR_DELETE_RECORD','trans_label'=>'Please select a record number to delete the account.'),
	array('module'=>'Users','label'=>'LBL_MERGE_MSG','trans_label'=>'Select a module for this template to be assigned to'),
	array('module'=>'Users','label'=>'LNK_GO_TO_TOP','trans_label'=>'Go to top of the page'),
	array('module'=>'Users','label'=>'LBL_BODY','trans_label'=>'email Body text'),
	array('module'=>'Users','label'=>'LBL_TAB_MENU_UPDATED','trans_label'=>'Tab Menu Updated! Please go to '),
	array('module'=>'Users','label'=>'LBL_BASIC_PROFILE_DETAILS','trans_label'=>'Basic profile details'),
	array('module'=>'Users','label'=>'LBL_STD_MESG_OPTION','trans_label'=>'Select the standard actions to be allowed'),
	array('module'=>'Users','label'=>'LBL_UTILITY_MESG_OPTION','trans_label'=>'Select the utility actions to be authorised'),
	array('module'=>'Users','label'=>'LBL_FIELD_MESG_OPTION','trans_label'=>'Select the fields to be authorised'),
	array('module'=>'Users','label'=>'LBL_SELECT_CHOICE_NEW_PROFILE','trans_label'=>'Select how to create the new profile'),
	array('module'=>'Users','label'=>'LBL_ACCESS_RIGHTS_FOR_MODULES','trans_label'=>'Access rights for linked modules'),
	array('module'=>'Users','label'=>'LBL_SPECIFY_ROLE_NAME','trans_label'=>'Specify a name for the new role :'),
	array('module'=>'Users','label'=>'LBL_EMAIL_SCHDS_DESC','trans_label'=>'list of notifications that are activated when the corresponding event has ended.'),
	array('module'=>'Users','label'=>'LBL_TASK_NOTIFICATION_DESCRITPION','trans_label'=>'Notify when a task is delayed for more then 24 hrs.'),
	array('module'=>'Users','label'=>'LBL_TICKETS_DESCRIPTION','trans_label'=>'Notify the status of pending tickets'),
	array('module'=>'Users','label'=>'LBL_START_DESCRIPTION','trans_label'=>'Notify including the start of the support/service'),
	array('module'=>'Users','label'=>'LBL_ACTIVITY_REMINDER_DESCRIPTION','trans_label'=>'Notify before the start of  an event, based on the reminder settings'),
	array('module'=>'Users','label'=>'INV_TANDC','trans_label'=>'Terms & conditions'),
	array('module'=>'Users','label'=>'INV_TERMSANDCONDITIONS','trans_label'=>'Inventory Terms & Conditions'),
	array('module'=>'Users','label'=>'LBL_INV_NOT_DESC','trans_label'=>'List of notifications that will be sent to the product responsible person/purchaser, indicating the required quantity and the current stock level during the creation of a Quote, Sales Order and Invoice.'),
	array('module'=>'Users','label'=>'InvoiceNotification','trans_label'=>'Stock Notification during Invoice Generation'),
	array('module'=>'Users','label'=>'InvoiceNotificationDescription','trans_label'=>'When the stock level goes below the re-order level, a notification will be sent to the product responsible/purchaser'),
	array('module'=>'Users','label'=>'QuoteNotification','trans_label'=>'Stock Notification during Quote Generation'),
	array('module'=>'Users','label'=>'QuoteNotificationDescription','trans_label'=>'If the quantity of products mentioned in the quote is higher than the physical stock, a message will be send to the product responsible/purchaser.'),
	array('module'=>'Users','label'=>'SalesOrderNotification','trans_label'=>'Stock Notification during Sales Order Generation'),
	array('module'=>'Users','label'=>'SalesOrderNotificationDescription','trans_label'=>'If the quantity of products mentioned in the sales order is higher than the physical stock, a message will be send to the product responsible/purchaser.'),
	array('module'=>'Users','label'=>'LBL_GLOBAL_ACCESS_PRIVILEGES','trans_label'=>'organisation-level Sharing Rules'),
	array('module'=>'Users','label'=>'LBL_USER_IMAGE_INFORMATION','trans_label'=>'User image'),
	array('module'=>'Users','label'=>'Email','trans_label'=>'email'),
	array('module'=>'Users','label'=>'User Image','trans_label'=>'User image'),
	array('module'=>'Users','label'=>'LBL_PROFILE_TO_BE_DELETED','trans_label'=>'Profile to be Detected'),
	array('module'=>'Users','label'=>'LBL_RECALC_MSG','trans_label'=>'Are you sure, you want to Recalculate Sharing Access?'),
	array('module'=>'Users','label'=>'LBL_ADD_MAIL_ACCOUNT','trans_label'=>'Add e-mail account'),
	array('module'=>'Users','label'=>'LBL_NEW_MAIL_ACCOUNT_TITLE','trans_label'=>'New e-mail account [Alt+M]'),
	array('module'=>'Users','label'=>'LBL_NEW_MAIL_ACCOUNT_LABEL','trans_label'=>'New e-mail account'),
	array('module'=>'Users','label'=>'LBL_TEST_SETTINGS','trans_label'=>'Test my account setting now'),
	array('module'=>'Users','label'=>'LBL_DONOT_VAL_SSL_CERT','trans_label'=>'Do Not Validate SSL Certificate'),
	array('module'=>'Users','label'=>'LBL_LIST_MAIL_ACCOUNT','trans_label'=>'  List e-mail account'),
	array('module'=>'Users','label'=>'LBL_EMAIL_ID','trans_label'=>'email address'),
	array('module'=>'Users','label'=>'LBL_FORE_LASTNAME','trans_label'=>'First or Last name'),
	array('module'=>'Users','label'=>'LBL_LDAP','trans_label'=>'LDAP authentication'),
	array('module'=>'Users','label'=>'LBL_AD','trans_label'=>'Active Directory authentication'),
	array('module'=>'Users','label'=>'Disable Sunday on Week','trans_label'=>'Disable Sunday in week view'),
	array('module'=>'Users','label'=>'LBL_GROUPNAME_EXIST','trans_label'=>'A group with this name already exists!'),
	array('module'=>'Users','label'=>'LBL_PROFILENAME_EXIST','trans_label'=>'A Profile with this name Already Exists!'),
	array('module'=>'Users','label'=>'LBL_RECOVER_EMAIL_BODY1','trans_label'=>'The password for your account was recovered.<br />To run this operation please click'),
	array('module'=>'Users','label'=>'LBL_RECOVER_MAIL_ERROR','trans_label'=>'We are unable to send mail.<br />Contact the administrator and request a password change.'),
	array('module'=>'Users','label'=>'LBL_RECOVERY_SYSTEM1','trans_label'=>'Welcome to the password recovery system.<br />If you are not a user'),
	array('module'=>'Users','label'=>'LBL_RECOVERY_SYSTEM3','trans_label'=>'or fill out the fields below to replace the old password.'),
	array('module'=>'Users','label'=>'LBL_RECOVERY_SESSION_EXPIRED','trans_label'=>'Session timed out. Please repeat the password recovery process.'),
	array('module'=>'Users','label'=>'LBL_USER_BLOCKED','trans_label'=>'The user is blocked because he/she has not been using the account for more then %s months. Please contact your  administrator to reactivate it.'),
	array('module'=>'Users','label'=>'LBL_PASSWORD_TO_BE_CHANGED','trans_label'=>'Please change your password every %s months.'),
	array('module'=>'Users','label'=>'LBL_NOT_SAFETY_PASSWORD','trans_label'=>'The password does not meet the safety criteria:Use  at least %s characters, with no reference to User Name, Name or Last name.'),
	array('module'=>'Users','label'=>'LBL_AVATAR_INSTRUCTIONS','trans_label'=>'You have to insert the image before you set the avatar.'),
	array('module'=>'Users','label'=>'LBL_NOT_SUMMARY_INFO','trans_label'=>'If you choose to be notified via VTE, you will receive email messages of unread notifications. You can configure this in the ModNotifications script in crontab.'),
	array('module'=>'Vendors','label'=>'307-Service-Hardware Labor','trans_label'=>'307-Service-Hardware Labour'),
	array('module'=>'Vendors','label'=>'Created Time','trans_label'=>'Time created'),
	array('module'=>'Settings','label'=>'Percent','trans_label'=>'Percentage'),
	array('module'=>'Settings','label'=>'EMAILTEMPLATES','trans_label'=>'email Templates'),
	array('module'=>'Settings','label'=>'LBL_DEFAULT_ORGANIZATION_FIELDS','trans_label'=>'Default organisation Fields Access'),
	array('module'=>'Settings','label'=>'LBL_SETTING_DEFAULT_ORGANIZATION_FIELDS','trans_label'=>' - Setting Default Field Access within the organisation'),
	array('module'=>'Settings','label'=>'LBL_SETTING_FIELD_ACCESSIBILITY','trans_label'=>' - Setting Field Accessibility for each profile'),
	array('module'=>'Settings','label'=>'LBL_EDIT_PICKLIST_VALUES','trans_label'=>' - Edit pick list values'),
	array('module'=>'Settings','label'=>'LBL_SCHEDULE_EMAIL_NOTIFICATION','trans_label'=>' - Schedule email messages'),
	array('module'=>'Settings','label'=>'LBL_ADD_MAIL_ACCOUNT','trans_label'=>'Add e-mail account'),
	array('module'=>'Settings','label'=>'LBL_NEW_MAIL_ACCOUNT_TITLE','trans_label'=>'New e-mail account [Alt+M]'),
	array('module'=>'Settings','label'=>'LBL_NEW_MAIL_ACCOUNT_LABEL','trans_label'=>'New e-mail account'),
	array('module'=>'Settings','label'=>'LBL_TEST_SETTINGS','trans_label'=>'Test my account setting now'),
	array('module'=>'Settings','label'=>'LBL_LIST_MAIL_ACCOUNT','trans_label'=>'  List e-mail Account'),
	array('module'=>'Settings','label'=>'LBL_EMAIL_ID','trans_label'=>'email address'),
	array('module'=>'Settings','label'=>'LBL_INV_NOT_DESC','trans_label'=>'List of notifications that will be sent to the product responsible person/purchaser, indicating the required quantity and the current stock level during the creation of a Quote, Sales Order and Invoice.'),
	array('module'=>'Settings','label'=>'InvoiceNotification','trans_label'=>'Stock Notification during Invoice Generation'),
	array('module'=>'Settings','label'=>'InvoiceNotificationDescription','trans_label'=>'When the stock level goes below the re-order level, a notification will be sent to the product responsible/purchaser'),
	array('module'=>'Settings','label'=>'leadCustomFieldDescription','trans_label'=>'Map each of your organisations lead custom fields to each of your custom account'),
	array('module'=>'Settings','label'=>'LBL_ASSIGN_MODULE_OWNERS_INFO','trans_label'=>' - Assign Owners for each module'),
	array('module'=>'Settings','label'=>'LBL_ROLE_DESCRIPTION','trans_label'=>'Set up role hierarchy and assign to the users'),
	array('module'=>'Settings','label'=>'LBL_SHARING_FIELDS_DESCRIPTION','trans_label'=>'Define global field-level access for each module'),
	array('module'=>'Settings','label'=>'LBL_EMAIL_TEMPLATE_DESCRIPTION','trans_label'=>'Manage templates for email module'),
	array('module'=>'Settings','label'=>'LBL_INV_TANDC_DESCRIPTION','trans_label'=>'Specify the Terms and Conditions for quotes, orders, and invoices'),
	array('module'=>'Settings','label'=>'LBL_COMPANY_DESCRIPTION','trans_label'=>'Specify the business address of company'),
	array('module'=>'Settings','label'=>'LBL_BACKUP_SERVER_DESCRIPTION','trans_label'=>'Specify the database backup server details'),
	array('module'=>'Settings','label'=>'LBL_TAX_DESCRIPTION','trans_label'=>'Manage taxes and  tax rates'),
	array('module'=>'Settings','label'=>'LBL_PROXY_DESCRIPTION','trans_label'=>'Configure proxies to access RSS feeds through the Internet'),
	array('module'=>'Settings','label'=>'LBL_AUDIT_DESCRIPTION','trans_label'=>'Display data operations performed by users'),
	array('module'=>'Settings','label'=>'LBL_COMPANY_DESC','trans_label'=>'Specify the business address of your company'),
	array('module'=>'Settings','label'=>'LBL_INVEN_TANDC_DESC','trans_label'=>'Specify the text for the Terms & Conditions section of Quotes, Orders, and Invoices modules'),
	array('module'=>'Settings','label'=>'LBL_GROUP_DESC','trans_label'=>'Manage different types of user groups within your organisation'),
	array('module'=>'Settings','label'=>'LBL_ANNOUNCEMENT_INFO','trans_label'=>'Type the announcement text below, then click \'Update\'.'),
	array('module'=>'Settings','label'=>'LBL_ANNOUNCEMENT_DESC','trans_label'=>'Change the text in the textbox at the top of each page'),
	array('module'=>'Settings','label'=>'LBL_PROXY_SERVER_DESC','trans_label'=>'Configure proxies to access RSS feeds through the Internet'),
	array('module'=>'Settings','label'=>'LBL_LENGTHALERT','trans_label'=>'Sorry, you can cannot map fields with different character sizes. Kindly map the data with same or more character size.'),
	array('module'=>'Settings','label'=>'LBL_DECIMALALERT','trans_label'=>'Sorry, you can cannot map fields with different character sizes. Kindly map the data with same or more character size.'),
	array('module'=>'Settings','label'=>'LBL_TASK_NOTIFICATION_DESCRITPION','trans_label'=>'Notify when a task is delayed for more then 24 hrs.'),
	array('module'=>'Settings','label'=>'LBL_TICKETS_DESCRIPTION','trans_label'=>'Notify the status of pending tickets'),
	array('module'=>'Settings','label'=>'LBL_START_DESCRIPTION','trans_label'=>'Notify including the start of the support/service'),
	array('module'=>'Settings','label'=>'LBL_ACTIVITY_REMINDER_DESCRIPTION','trans_label'=>'Notify before the start of  an event, based on the reminder settings'),
	array('module'=>'Settings','label'=>'QuoteNotificationDescription','trans_label'=>'If the quantity of products mentioned in the quote is higher than the physical stock, a message will be send to the product responsible/purchaser.'),
	array('module'=>'Settings','label'=>'SalesOrderNotificationDescription','trans_label'=>'If the quantity of products mentioned in the sales order is higher than the physical stock, a message will be send to the product responsible/purchaser.'),
	array('module'=>'Settings','label'=>'QuoteNotification','trans_label'=>'Stock Notification during Quote Generation'),
	array('module'=>'Settings','label'=>'SalesOrderNotification','trans_label'=>'Stock Notification during Sales Order Generation'),
	array('module'=>'Settings','label'=>'LBL_GLOBAL_ACCESS_PRIVILEGES','trans_label'=>'organisation-level Sharing Rules'),
	array('module'=>'Settings','label'=>'LBL_RECALC_MSG','trans_label'=>'Are you sure, you want to Recalculate Sharing Access?'),
	array('module'=>'Settings','label'=>'LBL_ACCESS_RIGHTS_FOR_MODULES','trans_label'=>'Access rights for linked modules'),
	array('module'=>'Settings','label'=>'LBL_DOC_MSWORD','trans_label'=>'Please use a document with the next format: doc/msword, or OpenOffice/odt or Rich Text Format/rtf'),
	array('module'=>'Settings','label'=>'LOGO_ERROR','trans_label'=>'Only  jpeg/png formats are allowed'),
	array('module'=>'Settings','label'=>'File_has_no_data','trans_label'=>'File is empty'),
	array('module'=>'Settings','label'=>'uploaded_file_exceeds_maximum_limit','trans_label'=>'the uploaded file exceeds the maximum VTE file size'),
	array('module'=>'Settings','label'=>'LBL_CHECK_ASSIGNEDTO_MAILID','trans_label'=>'Please check the email address of'),
	array('module'=>'Settings','label'=>'LBL_MAILSENDERROR','trans_label'=>'Mail could not be sent to the admin user. Please check the admin email address/Server settings'),
	array('module'=>'Settings','label'=>'FILESIZE_EXCEEDS_INFO_CONFIG_INC','trans_label'=>'Sorry, the uploaded file exceeds the maximum file sizet in config.inc.php.'),
	array('module'=>'Settings','label'=>'FILESIZE_EXCEEDS_INFO_PHP_INI','trans_label'=>'Sorry, the uploaded file exceeds the maximum file sizet in php.ini. '),
	array('module'=>'Settings','label'=>'LBL_SUPPORT_DESCRIPTION','trans_label'=>'Notify one month before the support ends.'),
	array('module'=>'Settings','label'=>'LBL_SUPPORT_DESCRIPTION_MONTH','trans_label'=>'Notify one week before the support ends.'),
	array('module'=>'Settings','label'=>'LBL_PICKLIST_GLOBAL_DELETE','trans_label'=>'Delete all data'),
	array('module'=>'Settings','label'=>'LBL_PICKLIST_TRANSFER','trans_label'=>'Transferring the values Of '),
	array('module'=>'Settings','label'=>'LBL_COLORED_LISTVIEW_EDITOR','trans_label'=>'List View Colours'),
	array('module'=>'Settings','label'=>'LBL_COLORED_LISTVIEW_DESCRIPTION','trans_label'=>'Configure colours of List Views'),
	array('module'=>'Settings','label'=>'LBL_FAX_SERVER_DESC','trans_label'=>'Configure your Outgoing Fax Server'),
	array('module'=>'Settings','label'=>'LBL_FAX_PREFIX','trans_label'=>'Prefix for fax numbers'),
	array('module'=>'Settings','label'=>'LBL_SMS_SERVER_DESC','trans_label'=>'Configure your Outgoing Sms Server'),
	array('module'=>'Settings','label'=>'LBL_SMS_PREFIX','trans_label'=>'Prefix for sms numbers'),
	array('module'=>'Settings','label'=>'ASTERISK_PORT_TITLE','trans_label'=>'The port to which the asterisk call manager API can connect to Asterisk (default 5038)'),
	array('module'=>'Settings','label'=>'LBL_NewState','trans_label'=>'Change ticket status to'),
	array('module'=>'Settings','label'=>'LBL_MODULE_MANAGEMENT_RELATEDLIST','trans_label'=>'Creation of Related List'),
	array('module'=>'Settings','label'=>'LBL_MODULE_MANAGEMENT_MODULE','trans_label'=>'Creation of Module'),
	array('module'=>'Settings','label'=>'LBL_PICKLIST_DESCRIPTION_MULTI','trans_label'=>'Personalise values for Pick list multi-language in every module'),
	array('module'=>'Settings','label'=>'LBL_LAYOUT_EDITOR_DESCRIPTION','trans_label'=>'Design and Modify the layout for each module'),
	array('module'=>'Settings','label'=>'VTLIB_LBL_MODULE_MANAGER_DESCRIPTION','trans_label'=>'Manage Module behaviour inside VTE'),
	array('module'=>'Settings','label'=>'VTLIB_LBL_MODULENAME_MISMATCH','trans_label'=>'Module name mismatch'),
	array('module'=>'Settings','label'=>'VTLIB_LBL_CANNOT_UPGRADE','trans_label'=>'Cannot upgrade!'),
	array('module'=>'Settings','label'=>'LBL_USERNAME_EXIST','trans_label'=>'Username Already Exists!'),
	array('module'=>'Settings','label'=>'LBL_GROUPNAME_EXIST','trans_label'=>'A group with this name already exists!'),
	array('module'=>'Settings','label'=>'PORTAL_EXTENSION_DESCRIPTION','trans_label'=>'Allows you to Configure the Customer Portal Plugin'),
	array('module'=>'Settings','label'=>'LBL_EVERYTIME_RECORD_SAVED','trans_label'=>'Always when the the record is saved'),
	array('module'=>'Settings','label'=>'LBL_ON_MODIFY','trans_label'=>'Always when a record is modified'),
	array('module'=>'Settings','label'=>'ERR_INVALID_PROFILE_ID','trans_label'=>'invalid Profile address. Please enter correct Profile address'),
	array('module'=>'Settings','label'=>'LBL_PRIVACY_DESC','trans_label'=>'To improve the VTE application, we collect a minimum of information from your installation. E.g. the vtecrm.com user that activates the system, the folder it has been installed in and the number of users. This is the same information needed to activate the application. We do not collect (information on ) your data, or the mail server you use. It helps us to understand how many people are enjoying VTE worldwide. The information is only updated when the administrator logs in.'),
	array('module'=>'Settings','label'=>'LBL_ERR_DELETE_MAIL_TEMPLATE_NEWSLETTER','trans_label'=>'Some templates are linked to newsletters. Deleting them may cause a problem. Do you want to proceed?'),
	array('module'=>'Settings','label'=>'LBL_UT208_TYPEPWD_DESC','trans_label'=>'Restore the field by removing the password protection.'),
	array('module'=>'Settings','label'=>'LBL_FORGET_PWD_ALERT','trans_label'=>'If you forget the password, data will be lost and cannot be recovered..'),
	array('module'=>'Settings','label'=>'LBL_UT208_FILTER_IP_DESC','trans_label'=>'Only specified IP addresses can decrypt the field. Several values can be specified, separated by a space. E.g. 192.168.1.45 10.0.1.0/24'),
	array('module'=>'CustomView','label'=>'LBL_AF_HDR1','trans_label'=>'Set the search conditions to further shorten the list.'),
	array('module'=>'CustomView','label'=>'LBL_AF_HDR2','trans_label'=>'You can use "or" filters by entering multiple items in the third column.'),
	array('module'=>'CustomView','label'=>'LBL_AF_HDR3','trans_label'=>'You can enter up to 10 items, separated by commas. For example: CA, NY, TX, FL searches for CA or NY or TX or FL.'),
	array('module'=>'CustomView','label'=>'LBL_AF_HDR4','trans_label'=>'If "Activity Type" is selected, give any one of the following values "Call","Meeting" or "Task".'),
	array('module'=>'CustomView','label'=>'Created Time','trans_label'=>'Time created'),
	array('module'=>'CustomView','label'=>'industry','trans_label'=>'Industry'),
	array('module'=>'CustomView','label'=>'Birthdate','trans_label'=>'Date of birth'),
	array('module'=>'CustomView','label'=>'Actual Response Count','trans_label'=>'Actual number of responses'),
	array('module'=>'CustomView','label'=>'LBL_AF_HDR5','trans_label'=>'Simple Time Filter that allows you to select date based on <b>Account Created Time</b> or <b>Account Modified Time</b>'),
	array('module'=>'Administration','label'=>'ERR_DELETE_RECORD','trans_label'=>'Please specify a record number to delete the account.'),
	array('module'=>'Picklistmulti','label'=>'LBL_SUCCESS','trans_label'=>'Operation completed successfully'),
	array('module'=>'Picklistmulti','label'=>'LBL_MANDATORY','trans_label'=>'Fields marked with (*) are mandatory'),
	array('module'=>'Import','label'=>'ERR_FILE_DOESNT_EXIST','trans_label'=>'File does not exist'),
	array('module'=>'Import','label'=>'ERR_CANT_OPEN_FILE','trans_label'=>'Cannot open the file'),
	array('module'=>'Import','label'=>'ERR_UNIMPORTED_RECORDS_IN_QUEUE','trans_label'=>'User still has unimported records in queue'),
	array('module'=>'Import','label'=>'ERR_FILE_READ_FAILED','trans_label'=>'File cannot be read'),
	array('module'=>'Import','label'=>'ERR_UNIMPORTED_RECORDS_EXIST','trans_label'=>'There are still some unimported records in your import queue, blocking you from importing more data.<br>Delete the records and start a new import'),
	array('module'=>'Import','label'=>'ERR_FAILED_TO_LOCK_MODULE','trans_label'=>'Failed to lock the module for import. Please try again later'),
	array('module'=>'Import','label'=>'ERR_MODULE_IMPORT_LOCKED','trans_label'=>'Import cannot be executed, another import is in progress. Try again later.'),
	array('module'=>'Import','label'=>'ERR_IMPORT_INTERRUPTED','trans_label'=>'The import has been stopped. Please try again later.'),
	array('module'=>'Help','label'=>'ERR_DELETE_RECORD','trans_label'=>'Please specify a record number to delete the account.'),
	array('module'=>'com_vtiger_workflow','label'=>'VTCreateTodoTask','trans_label'=>'Create To-do'),
	array('module'=>'com_vtiger_workflow','label'=>'LBL_EDIT_TASK_TITLE','trans_label'=>'Edit an existing task or create a new task'),
	array('module'=>'com_vtiger_workflow','label'=>'LBL_EDIT_WORKFLOW_TITLE','trans_label'=>'Edit an existing workflow or create a new workflow'),
	array('module'=>'com_vtiger_workflow','label'=>'LBL_VALIDATION_MISSING_MANDATORY_FIELDS','trans_label'=>'Please fill out the mandatory fields.'),
	array('module'=>'com_vtiger_workflow','label'=>'LBL_VALIDATION_INVALID_DATE_RANGE','trans_label'=>'Start date/time is later then the end date/time'),
	array('module'=>'com_vtiger_workflow','label'=>'LBL_ERROR_NO_WORKFLOW','trans_label'=>'This workflow  does not exist'),
	array('module'=>'com_vtiger_workflow','label'=>'LBL_ERROR_NO_TASK','trans_label'=>'This task does not exist'),
	array('module'=>'com_vtiger_workflow','label'=>'LBL_ERROR_NOT_ADMIN','trans_label'=>'You are not authorised to access this module.'),
	array('module'=>'com_vtiger_workflow','label'=>'LBL_WORKFLOW_NOTE_CRON_CONFIG','trans_label'=>'NOTE: Please configure the Workflow cron script.'),
	array('module'=>'Yahoo','label'=>'ERR_DELETE_RECORD','trans_label'=>'Please select a record number to delete the account.'),
	array('module'=>'APP_STRINGS','label'=>'Attachments','trans_label'=>'Attachments'),
	array('module'=>'APP_STRINGS','label'=>'Today','trans_label'=>'Today\'s'),
	array('module'=>'APP_STRINGS','label'=>'USERS','trans_label'=>'Users'),
	array('module'=>'APP_STRINGS','label'=>'TO','trans_label'=>'To:'),
	array('module'=>'APP_STRINGS','label'=>'invoice no','trans_label'=>'Invoice No'),
	array('module'=>'APP_STRINGS','label'=>'NOTE','trans_label'=>'Document'),
	array('module'=>'APP_STRINGS','label'=>'quote','trans_label'=>'Quote'),
	array('module'=>'APP_STRINGS','label'=>'total','trans_label'=>'Total Amount'),
	array('module'=>'APP_STRINGS','label'=>'Timecard','trans_label'=>'Interventions'),
	array('module'=>'APP_LIST_STRINGS','label'=>'moduleList','trans_label'=>'{"Home":"Home","Dashboard":"Dashboard","Leads":"Leads","Contacts":"Contacts","Accounts":"Accounts","Potentials":"Potentials","Campaigns":"Campaigns","Notes":"Documents","Emails":"Email","Activities":"Activities","Products":"Products","HelpDesk":"Trouble Tickets","TimeCard":"Timecards","Faq":"FAQ","Calendar":"Calendar","Quotes":"Quotes","PurchaseOrder":"PurchaseOrder","Invoice":"Invoice","Rss":"RSS","Reports":"Reports","Vendors":"Vendors","PriceBooks":"PriceBooks","SalesOrder":"SalesOrder","Portal":"My Sites","Projects":"Projects","Visitreport":"Visitreport"}'),
	array('module'=>'Fax','label'=>'LBL_CONF_EXTENSION_ERROR','trans_label'=>'This file has an invalid format, please use a PDF,TIFFor PS file'),
	array('module'=>'Fax','label'=>'LBL_FAXSELECT_INFO','trans_label'=>'has the following Fax numbers associated .Please Select the Fax numbers to which the fax should be sent'),
	array('module'=>'Fax','label'=>'LBL_NO_RCPTS_FAX_ERROR','trans_label'=>'No recipients specified'),
	array('module'=>'Fax','label'=>'LBL_FAXSELECT_INFO3','trans_label'=>'You are not authorised to view fax numbers of the selected Record(s).'),
	array('module'=>'Fax','label'=>'LBL_PLEASE_ATTACH','trans_label'=>'Please select a valid file to attach and try again!'),
	array('module'=>'Fax','label'=>'LBL_EXCEED_MAX','trans_label'=>'Sorry, the uploaded file exceeds the maximum file size. Please try a file smaller than '),
	array('module'=>'Fax','label'=>'LBL_CHECK_USER_FAXID','trans_label'=>'Please check the current user\'s fax number.'),
	array('module'=>'Fax','label'=>'MESSAGE_FAX_COULD_NOT_BE_SEND','trans_label'=>'Fax could not be sent to the assigned user.'),
	array('module'=>'Fax','label'=>'MESSAGE_PLEASE_CHECK_ASSIGNED_USER_FAXID','trans_label'=>'Please check the user\'s fax number'),
	array('module'=>'Fax','label'=>'MESSAGE_PLEASE_CHECK_THE_FROM_FAXID','trans_label'=>'Please check the fax number of'),
	array('module'=>'Fax','label'=>'MESSAGE_FAX_COULD_NOT_BE_SEND_TO_THIS_FAXID','trans_label'=>'Fax could not be sent to this fax number'),
	array('module'=>'Fax','label'=>'MESSAGE_FAX_ID_IS_INCORRECT','trans_label'=>'Fax number is incorrect. Please check the number'),
	array('module'=>'Fax','label'=>'PLEASE_CHECK_THIS_FAXID','trans_label'=>'Please check this fax number.'),
	array('module'=>'Fax','label'=>'LBL_FAXSELECT_INFO1','trans_label'=>'The following Fax number types are associated to the selected'),
	array('module'=>'Fax','label'=>'LBL_FAXSELECT_INFO2','trans_label'=>'Select the Fax number types to which, the fax should be sent'),
	array('module'=>'Fax','label'=>'SELECT_FAX','trans_label'=>'Select Fax numbers'),
	array('module'=>'Fax','label'=>'MESSAGE_NO_SUBJECT','trans_label'=>'Subject field is empty. Do you want to continue?'),
	array('module'=>'Fax','label'=>'LBL_NO_RCPTS_EMAIL_ERROR','trans_label'=>'No recipients specified'),
	array('module'=>'ModComments','label'=>'Created Time','trans_label'=>'Time created'),
	array('module'=>'ModComments','label'=>'LBL_PLEASE_SELECT_REGION','trans_label'=>'Please select a part of the image'),
	array('module'=>'Webforms','label'=>'LBL_SUCCESS','trans_label'=>'entry is added to VTE CRM.'),
	array('module'=>'Webforms','label'=>'LBL_FAILURE','trans_label'=>'Failed to add entry to VTE CRM.'),
	array('module'=>'Transitions','label'=>'LBL_STATUS_HIST_OLD_SALES_STAGE','trans_label'=>'Previous status'),
	array('module'=>'Transitions','label'=>'LBL_STATUS_HIST_NEW_SALES_STAGE','trans_label'=>'Next status'),
	array('module'=>'Transitions','label'=>'LBL_STATUS_NO_AVAILABLE_STATES','trans_label'=>'No status available'),
	array('module'=>'Transitions','label'=>'LBL_UNMAKE_TRANSITION','trans_label'=>'Unmanaged'),
	array('module'=>'Transitions','label'=>'LBL_CANT_SET_FIELD','trans_label'=>'Cannot set multiple status fields!'),
	array('module'=>'Transitions','label'=>'LBL_STATUS_BLOCK_ACTUAL_STATE','trans_label'=>'Actual status'),
	array('module'=>'Transitions','label'=>'LBL_INITIAL_STATE','trans_label'=>'Initial status'),
	array('module'=>'Transitions','label'=>'LBL_ST_MANAGER_DESCRIPTION','trans_label'=>'Enable/Disable status transitions'),
	array('module'=>'ServiceContracts','label'=>'Created Time','trans_label'=>'Time created'),
	array('module'=>'Conditionals','label'=>'LBL_CRITERIA_VALUE_MORE_EQUAL','trans_label'=>'More or equal to (>=)'),
	array('module'=>'Conditionals','label'=>'LBL_CRITERIA_VALUE_NOT_EQUAL','trans_label'=>'Is not equal to  (!=)'),
	array('module'=>'Services','label'=>'Created Time','trans_label'=>'Time created'),
	array('module'=>'Sms','label'=>'LBL_CONF_EXTENSION_ERROR','trans_label'=>'This file has an invalid format, please use a PDF,TIFFor PS file'),
	array('module'=>'Sms','label'=>'LBL_SMSSELECT_INFO','trans_label'=>'has the following Sms numbers associated. Please Select the Sms number to which the sms should be sent'),
	array('module'=>'Sms','label'=>'LBL_NO_RCPTS_SMS_ERROR','trans_label'=>'No recipients specified'),
	array('module'=>'Sms','label'=>'LBL_SMSSELECT_INFO3','trans_label'=>'You are not authorised to view sms numbers of the selected Record(s).'),
	array('module'=>'Sms','label'=>'LBL_PLEASE_ATTACH','trans_label'=>'Please select a valid file to attach and try again!'),
	array('module'=>'Sms','label'=>'LBL_EXCEED_MAX','trans_label'=>'Sorry, the uploaded file exceeds the maximum file size. Please try a file smaller than '),
	array('module'=>'Sms','label'=>'LBL_CHECK_USER_SMSID','trans_label'=>'Please check the current user\'s sms number.'),
	array('module'=>'Sms','label'=>'MESSAGE_PLEASE_CHECK_ASSIGNED_USER_SMSID','trans_label'=>'Please check the user\'s SMS number.'),
	array('module'=>'Sms','label'=>'MESSAGE_PLEASE_CHECK_THE_FROM_SMSID','trans_label'=>'Please check the sms number of'),
	array('module'=>'Sms','label'=>'MESSAGE_SMS_COULD_NOT_BE_SEND_TO_THIS_SMSID','trans_label'=>'Sms could not be sent to this sms number'),
	array('module'=>'Sms','label'=>'MESSAGE_SMS_ID_IS_INCORRECT','trans_label'=>'Sms number is incorrect. Please Check this Sms number...'),
	array('module'=>'Sms','label'=>'MESSAGE_SMS_SENT_SUCCESSFULLY','trans_label'=>' Sms\'s sent successfully!'),
	array('module'=>'Sms','label'=>'PLEASE_CHECK_THIS_SMSID','trans_label'=>'Please check this sms number'),
	array('module'=>'Sms','label'=>'MESSAGE_NO_SUBJECT','trans_label'=>'Subject field is empty. Do you want to continue?'),
	array('module'=>'Sms','label'=>'LBL_SMSSELECT_INFO1','trans_label'=>'The following Sms number types are associated to the selected'),
	array('module'=>'Sms','label'=>'LBL_SMSSELECT_INFO2','trans_label'=>'Select the Sms number types to which, the sms should be sent'),
	array('module'=>'Sms','label'=>'SELECT_SMS','trans_label'=>'Select Sms numbers'),
	array('module'=>'Sms','label'=>'MESSAGE_PLEASE_CHECK_FROM_THE_SMSID','trans_label'=>'Please check the sms number of'),
	array('module'=>'Sms','label'=>'LBL_NO_RCPTS_EMAIL_ERROR','trans_label'=>'No recipients specified'),
	array('module'=>'Sms','label'=>'MESSAGE_NO_DESCRIPTION','trans_label'=>'Please insert the message'),
	array('module'=>'FieldFormulas','label'=>'LBL_MODULE_INFO','trans_label'=>'Formulas defined for '),
	array('module'=>'FieldFormulas','label'=>'LBL_DELETE_EXPRESSION_CONFIRM','trans_label'=>'Are you sure you want to delete the expression?'),
	array('module'=>'SLA','label'=>'Time Elapsed Last Status Change','trans_label'=>'Time Elapsed since Last Status Change'),
	array('module'=>'SLA','label'=>'Time Elapsed Last Status Change','trans_label'=>'Time Elapsed since Last Status Change'),
	array('module'=>'HelpDesk','label'=>'Time Elapsed Last Status Change','trans_label'=>'Time Elapsed since Last Status Change'),
	array('module'=>'Targets','label'=>'LBL_TARGETS_INFORMATION','trans_label'=>'Target Information'),
	array('module'=>'Targets','label'=>'LBL_CUSTOM_INFORMATION','trans_label'=>'Custom Information'),
	array('module'=>'Targets','label'=>'LBL_DESCRIPTION_INFORMATION','trans_label'=>'Description Information:'),
	array('module'=>'Targets','label'=>'Created Time','trans_label'=>'Time created'),
	array('module'=>'Newsletter','label'=>'LBL_NEWSLETTER_INFORMATION','trans_label'=>'Newsletter Information'),
	array('module'=>'Newsletter','label'=>'LBL_CUSTOM_INFORMATION','trans_label'=>'Custom Information'),
	array('module'=>'Newsletter','label'=>'LBL_DESCRIPTION_INFORMATION','trans_label'=>'Description Information:'),
	array('module'=>'Newsletter','label'=>'Created Time','trans_label'=>'Time created'),
	array('module'=>'Newsletter','label'=>'LBL_TARGET_LIST_EMPTY','trans_label'=>'List is empty! Select at least one record with email'),
	array('module'=>'Newsletter','label'=>'LBL_TEST_MAIL_SENT','trans_label'=>'Test mail was sent'),
	array('module'=>'Newsletter','label'=>'LBL_SUCCESS_UNSUBSCRIPTION','trans_label'=>'Successfully Unsubscribed'),
	array('module'=>'Newsletter','label'=>'LBL_UNSUCCESS_UNSUBSCRIPTION','trans_label'=>'Unsubscription failed. Please contact admin@vte123abc987.com'),
	array('module'=>'Newsletter','label'=>'Bounce email','trans_label'=>'Bounced email'),
	array('module'=>'Visitreport','label'=>'LBL_DESCRIPTION_INFORMATION','trans_label'=>'Expenses'),
	array('module'=>'Visitreport','label'=>'Created Time','trans_label'=>'Time created'),
	array('module'=>'Visitreport','label'=>'spvitoall','trans_label'=>'Food & Accommodation costs'),
	array('module'=>'ProjectMilestone','label'=>'Project Milestone ID','trans_label'=>'Milestone address'),
	array('module'=>'ProjectMilestone','label'=>'Milestone Date','trans_label'=>'Milestone id'),
	array('module'=>'ProjectMilestone','label'=>'Created Time','trans_label'=>'Time created'),
	array('module'=>'ProjectTask','label'=>'Created Time','trans_label'=>'Time created'),
	array('module'=>'ProjectPlan','label'=>'Created Time','trans_label'=>'Time created'),
	array('module'=>'PDFMaker','label'=>'LBL_TEMPLATE_GENERATOR_DESCRIPTION','trans_label'=>'General pdf templates available for all modules.'),
	array('module'=>'PDFMaker','label'=>'LBL_CHANGE_MODULE_QUESTION','trans_label'=>'Are you sure you want to change the primary module.'),
	array('module'=>'PDFMaker','label'=>'LBL_ARTICLE','trans_label'=>'Product block'),
	array('module'=>'PDFMaker','label'=>'LBL_ARTICLE_START','trans_label'=>'block start'),
	array('module'=>'PDFMaker','label'=>'LBL_ARTICLE_END','trans_label'=>'block end'),
	array('module'=>'PDFMaker','label'=>'LBL_PRODUCT_FIELD_INFO','trans_label'=>'* fields are placed into Product block. Product block will be shown for every product/service in PDF.'),
	array('module'=>'PDFMaker','label'=>'LBL_NOPRODUCT_BLOC','trans_label'=>'Current module does not contain product block.'),
	array('module'=>'PDFMaker','label'=>'LBL_MISSING_FIELDS','trans_label'=>'Missing mandatory fields:'),
	array('module'=>'PDFMaker','label'=>'LBL_PRODUCT_BLOC_TPL','trans_label'=>'Product block template'),
	array('module'=>'PDFMaker','label'=>'LBL_VATBLOCK_VAT_PERCENT','trans_label'=>'TAX percentage'),
	array('module'=>'PDFMaker','label'=>'LBL_IGNORE_PICKLIST_VALUES_DESC','trans_label'=>'Enter the pick list values separated by a comma, commas will not show in the pdf templates. (i.e. --None--, --none--)'),
	array('module'=>'PDFMaker','label'=>'CRM_TEMPLATES_DONT_EXIST','trans_label'=>'No pdf templates were created for this module.'),
	array('module'=>'PDFMaker','label'=>'LBL_ENCODING_TITLE','trans_label'=>'Select the specific encoding to minimize the pdf file and time to process.'),
	array('module'=>'PDFMaker','label'=>'LBL_CUSTOM_DESC','trans_label'=>'In case some changes were made in files mentioned above of standard vte installation.'),
	array('module'=>'PDFMaker','label'=>'LBL_INSTRUCTIONS','trans_label'=>'Follow these instructions to install PDF Maker.'),
	array('module'=>'PDFMaker','label'=>'LBL_INSTAL_ERROR','trans_label'=>'Error occurred during installation of PDF Maker.'),
	array('module'=>'PDFMaker','label'=>'LBL_ERROR_TBL','trans_label'=>'These tasks failed to finish'),
	array('module'=>'PDFMaker','label'=>'LBL_INSERT_KEY','trans_label'=>'Please insert the license key that you received in the purchase confirmation email.'),
	array('module'=>'PDFMaker','label'=>'LBL_ONLINE_ASSURE','trans_label'=>'Please make sure that your server has internet connection in order to run validation.'),
	array('module'=>'PDFMaker','label'=>'LBL_DOWNLOAD_SRC','trans_label'=>'To generate pdf files please download and install the mPDF script.'),
	array('module'=>'PDFMaker','label'=>'LBL_WELCOME_DESC','trans_label'=>'This will install PDF Maker into  vtiger CRM.'),
	array('module'=>'PDFMaker','label'=>'LBL_MB_STRING_ERROR','trans_label'=>'mPdf script requires <strong>mb_string</strong> extension to be enabled in your PHP installation. Please enable for PDF Maker to work correctly.'),
	array('module'=>'PDFMaker','label'=>'LBL_BREAKLINE_DESC','trans_label'=>'Insert a Page Break after selected product.'),
	array('module'=>'PDFMaker','label'=>'LBL_REACTIVATE_DESC','trans_label'=>'In case a problem with the license key occurs while generating PDF files.'),
	array('module'=>'PDFMaker','label'=>'REACTIVATE_SUCCESS','trans_label'=>'You have successfully reactivated your PDF Maker.'),
	array('module'=>'PDFMaker','label'=>'LBL_UPDATE_INSTRUCTIONS','trans_label'=>'Follow these instructions to update PDF Maker'),
	array('module'=>'PDFMaker','label'=>'LBL_UPDATE_ERROR','trans_label'=>'Error occurred while updating PDF Maker.'),
	array('module'=>'PDFMaker','label'=>'LBL_DEACTIVATE_QUESTION','trans_label'=>'Do You really want to deactivate Your license key?'),
	array('module'=>'PDFMaker','label'=>'LBL_DEACTIVATE_DESC','trans_label'=>'After deactivation You can only export PDFMaker templates.<br /> After reactivation, standard functionality will resume.'),
	array('module'=>'ModNotifications','label'=>'LBL_MODNOTIFICATION_INFORMATION','trans_label'=>'Notification Information'),
	array('module'=>'ModNotifications','label'=>'LBL_CUSTOM_INFORMATION','trans_label'=>'Custom Information'),
	array('module'=>'ModNotifications','label'=>'LBL_DESCRIPTION_INFORMATION','trans_label'=>'Description Information:'),
	array('module'=>'ModNotifications','label'=>'Created Time','trans_label'=>'Time created'),
	array('module'=>'ChangeLog','label'=>'LBL_CHANGELOG_INFORMATION','trans_label'=>'Change Log Information'),
	array('module'=>'ChangeLog','label'=>'Created Time','trans_label'=>'Time created'),
	array('module'=>'Timecards','label'=>'NewState','trans_label'=>'Change ticket status to'),
	array('module'=>'Timecards','label'=>'FinishDate','trans_label'=>'End date'),
	array('module'=>'Timecards','label'=>'sortSeeWO','trans_label'=>'View Work orders'),
	array('module'=>'Timecards','label'=>'sortOrder','trans_label'=>'Sort Order'),
	array('module'=>'Timecards','label'=>'Err_NoAccountContact','trans_label'=>'Cannot convert because the ticket is not related to a Contact/Account'),
	array('module'=>'Timecards','label'=>'Err_ContactWithoutAccount','trans_label'=>'Cannot convert because the ticket is related to a Contact that is not linked to an account'),
	array('module'=>'Timecards','label'=>'Created Time','trans_label'=>'Time created'),
	array('module'=>'Morphsuit','label'=>'LBL_MORPHSUIT_INSTALLATION_LENGTH','trans_label'=>'Installation duration'),
	array('module'=>'Morphsuit','label'=>'LBL_MORPHSUIT_CODE_WRONG','trans_label'=>'Invalid activation key'),
	array('module'=>'Morphsuit','label'=>'LBL_MORPHSUIT_CODE_WRONG_TIME_EXPIRED','trans_label'=>'Obsolete activation key'),
	array('module'=>'Morphsuit','label'=>'LBL_MORPHSUIT_ACTIVATION_MAIL_OK','trans_label'=>'Mail has been sent to VTECRM Network service, check your inbox for the activation key.'),
	array('module'=>'Morphsuit','label'=>'LBL_MORPHSUIT_USER_NUMBER_EXCEEDED','trans_label'=>'Number of users exceeded the limit. Request a new license at your administrator.'),
	array('module'=>'Morphsuit','label'=>'LBL_MORPHSUIT_NEW_LICENSE_REGISTRATION','trans_label'=>'Do you want to save the new license now?'),
	array('module'=>'Morphsuit','label'=>'LBL_ERROR_VTE_FREE_CHECK','trans_label'=>'Error key. Verify number of  active users.'),
	array('module'=>'Morphsuit','label'=>'LBL_MORPHSUIT_USER_NUMBER_EXCEEDED_FREE','trans_label'=>'Number of users exceeded the Free version. Click \'OK\' if you want to upgrade to the Standard version of VTE.'),
	array('module'=>'Morphsuit','label'=>'LBL_ERROR_VTE_REGISTRATION','trans_label'=>'You have to sign up to www.crmvillage.biz'),
	array('module'=>'Morphsuit','label'=>'LBL_FUNCTION_BLOCKED','trans_label'=>'This function is only available in VTE ONSITE BUSINESS. If you want to continue and upgrade, please contact CRMVILLAGE at %s. Please specify how many users you want to enable.'),
	array('module'=>'Morphsuit','label'=>'LBL_MORPHSUIT_ROLE_NUMBER_EXCEEDED','trans_label'=>'You have exceeded the number of roles available in the FREE version.'),
	array('module'=>'Morphsuit','label'=>'LBL_MORPHSUIT_PROFILE_NUMBER_EXCEEDED','trans_label'=>'You have exceeded the number of profiles available in the FREE version.'),
	array('module'=>'Morphsuit','label'=>'LBL_MORPHSUIT_PDF_NUMBER_EXCEEDED','trans_label'=>'You have exceeded the number of pdf\'s available in the FREE version.'),
	array('module'=>'Morphsuit','label'=>'LBL_MORPHSUIT_ADV_SHARING_RULE_NUMBER_EXCEEDED','trans_label'=>'You have exceeded the number of advanced sharing rules available in the FREE version.'),
	array('module'=>'Morphsuit','label'=>'LBL_MORPHSUIT_SHARING_RULE_USER_NUMBER_EXCEEDED','trans_label'=>'You have exceeded the number of sharing rules owner based available in the FREE version.'),
	array('module'=>'Morphsuit','label'=>'LBL_ERROR_VTE_FREE_NOT_ACTIVABLE','trans_label'=>'This version is no valid. Install/Update to the latest version.'),
	array('module'=>'Morphsuit','label'=>'LBL_CONNECT_TO_ENABLE_VTE','trans_label'=>'Check the internet connection and login again to unlock VTECRM'),
	array('module'=>'Morphsuit','label'=>'LBL_OTHER_FREE_VERSION','trans_label'=>'Probably you have moved your VTE installation. Some functionality of this old installation is limited.'),
	array('module'=>'Morphsuit','label'=>'LBL_MORPHSUIT_ADMIN_CONFIG','trans_label'=>'Set the administrator'),
	array('module'=>'Morphsuit','label'=>'LBL_MORPHSUIT_OVERWRITE_CREDENTIALS','trans_label'=>'Admin user credentials will be overwritten by vtecrm.com credentials'),
	array('module'=>'CustomerPortal','label'=>'LBL_USER_DESCRIPTION','trans_label'=>'The above selected User profile will manage the fields shown in the Customer Portal'),
	array('module'=>'RecycleBin','label'=>'LBL_NO_PERMITTED_MODULES','trans_label'=>'No authorised modules available'),
	array('module'=>'Messages','label'=>'LBL_OTHER_INFORMATION','trans_label'=>'Other Information'),
	array('module'=>'Messages','label'=>'Created Time','trans_label'=>'Time created'),
	array('module'=>'Messages','label'=>'LBL_LEAVES_FETCH_IN','trans_label'=>'Keep emails on the server'),
	array('module'=>'ALERT_ARR','label'=>'OVERWRITE_EXISTING_ACCOUNT2','trans_label'=>') address details?\nIf you click Cancel the item is still linked keeping independent addresses.'),
	array('module'=>'ALERT_ARR','label'=>'CURRENCY_CONVERSION_INFO','trans_label'=>'Are you using Dollar $ as Currency?\nClick OK to remain as $, Cancel to change the currency conversion rate.'),
	array('module'=>'ALERT_ARR','label'=>'PLS_SELECT_VALID_FILE','trans_label'=>'Please select a file with the following extension:\n'),
	array('module'=>'ALERT_ARR','label'=>'LBL_PROVIDE_YES_NO','trans_label'=>' Invalid value.\nPlease Provide Yes or No'),
	array('module'=>'ALERT_ARR','label'=>'LBL_SELECT_CRITERIA','trans_label'=>' Invalid criteria.\nPlease select criteria'),
	array('module'=>'ALERT_ARR','label'=>'LBL_SELECT_COLUMN','trans_label'=>' Invalid column.\nPlease select column'),
	array('module'=>'ALERT_ARR','label'=>'OVERWRITE_EXISTING_CONTACT2','trans_label'=>') address details?\nIf you click Cancel the item is still linked keeping independent addresses.'),
);
foreach($new_en_us_translations as $t) {
	SDK::setLanguageEntry($t['module'], 'en_us', $t['label'], $t['trans_label']);
}
?>